FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npm install jsonwebtoken
RUN npm install cookie-parser
RUN npm install socket.io

COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]