-- ============================================================================
-- DEMI APPLICATION AND CLAIMS MANAGEMENT SYSTEM (DACMS)
-- Target Platform: PostgreSQL 15+
-- ============================================================================

-- 1. DROP EXISTING TABLES IN REVERSE ORDER OF DEPENDENCY
DROP TABLE IF EXISTS "SECURITY_TOKEN" CASCADE;
DROP TABLE IF EXISTS "NOTIFICATION" CASCADE;
DROP TABLE IF EXISTS "WORK_SESSION" CASCADE;
DROP TABLE IF EXISTS "REMUNERATION_CLAIM" CASCADE;
DROP TABLE IF EXISTS "DEMI_POSITION" CASCADE;
DROP TABLE IF EXISTS "DEMI_APPLICATION" CASCADE;
DROP TABLE IF EXISTS "DEMI_LISTING" CASCADE;
DROP TABLE IF EXISTS "STUDENT_MODULE_GRADE" CASCADE;
DROP TABLE IF EXISTS "MODULE_BUDGET" CASCADE;
DROP TABLE IF EXISTS "LECTURER_MODULE" CASCADE;
DROP TABLE IF EXISTS "NWU_MODULE" CASCADE;
DROP TABLE IF EXISTS "ORGANISATIONAL_ENTITY" CASCADE;
DROP TABLE IF EXISTS "SUPPORTING_DOCUMENT" CASCADE;
DROP TABLE IF EXISTS "ADMINISTRATOR" CASCADE;
DROP TABLE IF EXISTS "LECTURER" CASCADE;
DROP TABLE IF EXISTS "STUDENT" CASCADE;
DROP TABLE IF EXISTS "APP_USER" CASCADE;
DROP TABLE IF EXISTS "PAYMENT_SCALE" CASCADE;
DROP TABLE IF EXISTS "SYSTEM_ROLE" CASCADE;

-- 2. CREATE SYSTEM ROLE TABLE
CREATE TABLE "SYSTEM_ROLE" (
    "RoleID" INT GENERATED BY DEFAULT AS IDENTITY,
    "RoleName" varchar(20) NOT NULL,
    CONSTRAINT "PK_SYSTEM_ROLE" PRIMARY KEY ("RoleID"),
    CONSTRAINT "UQ_SYSTEM_ROLE_RoleName" UNIQUE ("RoleName")
);

-- 3. CREATE ORGANISATIONAL ENTITY TABLE
CREATE TABLE "ORGANISATIONAL_ENTITY" (
    "OE_ID" INT GENERATED BY DEFAULT AS IDENTITY,
    "OE_Code" varchar(10) NOT NULL,
    "OEName" varchar(150) NOT NULL,
    "FacultyName" varchar(100) DEFAULT 'Faculty of Natural & Agricultural Sciences',
    CONSTRAINT "PK_ORGANISATIONAL_ENTITY" PRIMARY KEY ("OE_ID"),
    CONSTRAINT "UQ_ORGANISATIONAL_ENTITY_OE_Code" UNIQUE ("OE_Code")
);

-- 4. CREATE ACADEMIC MODULES TABLE
CREATE TABLE "NWU_MODULE" (
    "ModuleID" INT GENERATED BY DEFAULT AS IDENTITY,
    "ModuleCode" varchar(10) NOT NULL,
    "ModuleName" varchar(100) NOT NULL,
    "Description" text,
    "MinAcademicRequirement" decimal(4,2) NOT NULL DEFAULT 65.00,
    "OE_ID" int NOT NULL,
    CONSTRAINT "PK_NWU_MODULE" PRIMARY KEY ("ModuleID"),
    CONSTRAINT "UQ_NWU_MODULE_ModuleCode" UNIQUE ("ModuleCode"),
    CONSTRAINT "FK_NWU_MODULE_ORGANISATIONAL_ENTITY" FOREIGN KEY ("OE_ID") REFERENCES "ORGANISATIONAL_ENTITY" ("OE_ID") DEFERRABLE INITIALLY IMMEDIATE
);

-- 5. CREATE PAYMENT SCALES TABLE
CREATE TABLE "PAYMENT_SCALE" (
    "ScaleID" INT GENERATED BY DEFAULT AS IDENTITY,
    "RoleLevel" varchar(50) NOT NULL,
    "StandardHourlyRate" decimal(8,2) NOT NULL,
    "EffectiveYear" int NOT NULL,
    CONSTRAINT "PK_PAYMENT_SCALE" PRIMARY KEY ("ScaleID")
);

-- 6. CREATE APPLICATION USER TABLE
CREATE TABLE "APP_USER" (
  "UserID" INT GENERATED BY DEFAULT AS IDENTITY,
  "Title" varchar(10) NOT NULL DEFAULT 'Mx',
  "FName" varchar(100) NOT NULL,
  "LName" varchar(100) NOT NULL,
  "Email" varchar(100) NOT NULL,
  "PasswordHash" varchar(255) NOT NULL,
  "RoleID" int NOT NULL,
  "CreatedAt" timestamptz DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "PK_APP_USER" PRIMARY KEY ("UserID"),
  CONSTRAINT "UQ_APP_USER_Email" UNIQUE ("Email"),
  CONSTRAINT "FK_APP_USER_SYSTEM_ROLE"
    FOREIGN KEY ("RoleID")
    REFERENCES "SYSTEM_ROLE" ("RoleID")
    DEFERRABLE INITIALLY IMMEDIATE
);

-- 7. CREATE STUDENT SUBTYPE TABLE (P&C122F FORM ALIGNED)
CREATE TABLE "STUDENT" (
    "StudentID" int NOT NULL,
    "StudentNumber" varchar(15) NOT NULL,
    "StudyLevel" varchar(20) NOT NULL,
    "ID_PassportNumber" varchar(20),
    "Title" varchar(10),
    "Gender" varchar(10),
    "DateOfBirth" date,
    "IncomeTaxNumber" varchar(20),
    "SACitizen" boolean DEFAULT true,
    "ResidentialAddress" text,
    "PostalAddress" text,
    "NextOfKinName" varchar(100),
    "NextOfKinMobile" varchar(20),
    "HighestQualification" varchar(100),
    "ContactDetails" varchar(50) NOT NULL,
    "BankName" varchar(50) NOT NULL,
    "AccountNumber" varchar(30) NOT NULL,
    "AccountType" varchar(20) DEFAULT 'Savings',
    "BranchCode" varchar(10) NOT NULL,
    "AccountHolderName" varchar(100),
    -- Added for StudentProfile.jsx (P&C122F) full-form coverage. Additive
    -- only: the blob columns above (ResidentialAddress/PostalAddress/
    -- HighestQualification) are untouched for seed-data compatibility.
    "Initials" varchar(10),
    "MiddleNames" varchar(100),
    "NickName" varchar(50),
    "Race" varchar(30),
    "MaritalStatus" varchar(20),
    "PreviousSurname" varchar(100),
    "HomeLanguage" varchar(30),
    "PreferenceLanguage" varchar(30),
    "Disability" varchar(3),
    "PrimaryEmploymentOutside" varchar(3),
    "StudentType" varchar(20),
    "Nationality" varchar(50),
    "CountryOfBirth" varchar(50),
    "CountryOfPassportIssue" varchar(50),
    "PermitNumber" varchar(30),
    "CurrentlyEmployedByNwu" varchar(3),
    "OeCodeAndName1" varchar(150),
    "JobName1" varchar(100),
    "OeCodeAndName2" varchar(150),
    "JobName2" varchar(100),

    "NextOfKinTitle" varchar(10),
    "NextOfKinInitials" varchar(10),
    "NextOfKinSurname" varchar(100),
    "NextOfKinRelationship" varchar(50),
    "NextOfKinDaytimePhoneNo" varchar(20),
    "IsNextOfKinNwuEmployee" varchar(3),
    "NextOfKinNwuNumber" varchar(20),

    "ResUnitNo" varchar(20),
    "ResComplex" varchar(100),
    "ResStreetNo" varchar(20),
    "ResStreetName" varchar(150),
    "ResSuburb" varchar(100),
    "ResTownCity" varchar(100),
    "ResPostalCode" varchar(10),
    "SameAsResidential" boolean DEFAULT true,
    "PoBoxNo" varchar(20),
    "PrivateBagNo" varchar(20),
    "PostOfficeBranch" varchar(100),
    "MailingPostalCode" varchar(10),
    "WorkPhoneNo" varchar(20),

    "QualificationInstitution" varchar(150),
    "QualificationType" varchar(100),
    "QualificationStatus" varchar(20),
    "QualificationAwardedDate" date,

    "AccountHolderRelationship" varchar(30),

    "DeclarationInitialsSurname" varchar(100),
    "DeclarationDate" date,
    "DeclarationAgreed" boolean DEFAULT false,
    "Signature" text,

    CONSTRAINT "PK_STUDENT" PRIMARY KEY ("StudentID"),
    CONSTRAINT "UQ_STUDENT_StudentNumber" UNIQUE ("StudentNumber"),
    CONSTRAINT "FK_STUDENT_APP_USER" FOREIGN KEY ("StudentID") REFERENCES "APP_USER" ("UserID") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE

);

-- 8. CREATE SUPPORTING DOCUMENTS TABLE
CREATE TABLE "SUPPORTING_DOCUMENT" (
    "DocumentID" INT GENERATED BY DEFAULT AS IDENTITY,
    "StudentID" int NOT NULL,
    "DocumentType" varchar(50) NOT NULL,
    "FilePath" varchar(255) NOT NULL,
    "UploadTimestamp" timestamptz DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_SUPPORTING_DOCUMENT" PRIMARY KEY ("DocumentID"),
    CONSTRAINT "FK_SUPPORTING_DOCUMENT_STUDENT" FOREIGN KEY ("StudentID") REFERENCES "STUDENT" ("StudentID") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

-- 9. CREATE LECTURER SUBTYPE TABLE
CREATE TABLE "LECTURER" (
    "LecturerID" int NOT NULL,
    "Department" varchar(100) NOT NULL,
    "OE_ID" int,
    CONSTRAINT "PK_LECTURER" PRIMARY KEY ("LecturerID"),
    CONSTRAINT "FK_LECTURER_APP_USER" FOREIGN KEY ("LecturerID") REFERENCES "APP_USER" ("UserID") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT "FK_LECTURER_ORGANISATIONAL_ENTITY" FOREIGN KEY ("OE_ID") REFERENCES "ORGANISATIONAL_ENTITY" ("OE_ID") DEFERRABLE INITIALLY IMMEDIATE
);

-- 10. CREATE LECTURER-MODULE MAPPING JUNCTION TABLE
CREATE TABLE "LECTURER_MODULE" (
    "LecturerID" int NOT NULL,
    "ModuleID" int NOT NULL,
    CONSTRAINT "PK_LECTURER_MODULE" PRIMARY KEY ("LecturerID", "ModuleID"),
    CONSTRAINT "FK_LECTURER_MODULE_LECTURER" FOREIGN KEY ("LecturerID") REFERENCES "LECTURER" ("LecturerID") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT "FK_LECTURER_MODULE_NWU_MODULE" FOREIGN KEY ("ModuleID") REFERENCES "NWU_MODULE" ("ModuleID") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

-- 11. CREATE ADMINISTRATOR SUBTYPE TABLE
CREATE TABLE "ADMINISTRATOR" (
    "AdminID" int NOT NULL,
    "TFASecret" text DEFAULT 'nosetup',
    "TFABackupCodes" text[] NOT NULL DEFAULT '{}',
    "TFALastStep" bigint,
    "TFAConfirmedAt" timestamptz,
    "BudgetAllocationRights" boolean DEFAULT true,
    CONSTRAINT "PK_ADMINISTRATOR" PRIMARY KEY ("AdminID"),
    CONSTRAINT "FK_ADMINISTRATOR_APP_USER" FOREIGN KEY ("AdminID") REFERENCES "APP_USER" ("UserID") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

-- 12. CREATE SECURITY SESSION TOKEN TABLE
CREATE TABLE "SECURITY_TOKEN" (
    "TokenID" INT GENERATED BY DEFAULT AS IDENTITY,
    "UserID" int NOT NULL,
    "JWT_Token" text NOT NULL,
    "IssuedAt" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "ExpiresAt" timestamptz NOT NULL,
    CONSTRAINT "PK_SECURITY_TOKEN" PRIMARY KEY ("TokenID"),
    CONSTRAINT "FK_SECURITY_TOKEN_APP_USER" FOREIGN KEY ("UserID") REFERENCES "APP_USER" ("UserID") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

-- 13. CREATE MODULE BUDGET TABLE
CREATE TABLE "MODULE_BUDGET" (
    "BudgetID" INT GENERATED BY DEFAULT AS IDENTITY,
    "ModuleID" int NOT NULL,
    "LecturerID" int NOT NULL,
    "AllocatedBudget" decimal(10,2) NOT NULL,
    "CurrentBudgetUsage" decimal(10,2) DEFAULT 0.00,
    "MaxAllowableWorkHours" int NOT NULL,
    "AcademicYear" int NOT NULL,
    CONSTRAINT "PK_MODULE_BUDGET" PRIMARY KEY ("BudgetID"),
    CONSTRAINT "FK_MODULE_BUDGET_NWU_MODULE" FOREIGN KEY ("ModuleID") REFERENCES "NWU_MODULE" ("ModuleID") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT "FK_MODULE_BUDGET_LECTURER" FOREIGN KEY ("LecturerID") REFERENCES "LECTURER" ("LecturerID") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

-- 14. CREATE STUDENT MODULE GRADE TABLE
CREATE TABLE "STUDENT_MODULE_GRADE" (
    "GradeID" INT GENERATED BY DEFAULT AS IDENTITY,
    "StudentID" int NOT NULL,
    "ModuleID" int NOT NULL,
    "GradeAchieved" decimal(5,2) NOT NULL,
    CONSTRAINT "PK_STUDENT_MODULE_GRADE" PRIMARY KEY ("GradeID"),
    CONSTRAINT "FK_STUDENT_MODULE_GRADE_STUDENT" FOREIGN KEY ("StudentID") REFERENCES "STUDENT" ("StudentID") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT "FK_STUDENT_MODULE_GRADE_NWU_MODULE" FOREIGN KEY ("ModuleID") REFERENCES "NWU_MODULE" ("ModuleID") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

-- 15. CREATE DEMI POSITION ADVERTISEMENT LISTING TABLE
CREATE TABLE "DEMI_LISTING" (
    "ListingID" INT GENERATED BY DEFAULT AS IDENTITY,
    "ModuleID" int NOT NULL,
    "LecturerID" int NOT NULL,
    "Deadline" timestamptz NOT NULL,
    "MinimumGrade" decimal(5,2) NOT NULL DEFAULT 65.00,
    CONSTRAINT "PK_DEMI_LISTING" PRIMARY KEY ("ListingID"),
    CONSTRAINT "FK_DEMI_LISTING_NWU_MODULE" FOREIGN KEY ("ModuleID") REFERENCES "NWU_MODULE" ("ModuleID") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT "FK_DEMI_LISTING_LECTURER" FOREIGN KEY ("LecturerID") REFERENCES "LECTURER" ("LecturerID") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

-- 16. CREATE DEMI APPLICATION TABLE
CREATE TABLE "DEMI_APPLICATION" (
    "ApplicationID" INT GENERATED BY DEFAULT AS IDENTITY,
    "StudentID" INT NOT NULL,
    "ListingID" INT NOT NULL,
    "Reference" VARCHAR(30) NOT NULL,
    "ApplicationStatus" VARCHAR(30) DEFAULT 'Pending',
    "VerificationEligibilityStatus" VARCHAR(30),
    "DateSubmitted" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    "AppReason" TEXT,
    "ReviewComment" TEXT,
    CONSTRAINT "PK_DEMI_APPLICATION" PRIMARY KEY ("ApplicationID"),
    CONSTRAINT "CHK_DEMI_APPLICATION_Status" CHECK (
        "ApplicationStatus" IN ('Pending', 'In Review', 'Approved', 'Rejected', 'Returned')
    )
);

-- Trigger function to generate demi application reference number
CREATE OR REPLACE FUNCTION generate_demi_application_reference()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    -- Fill only when the app did not provide one
    IF NEW."Reference" IS NULL OR btrim(NEW."Reference") = '' THEN
        SELECT
            'APP-' || TO_CHAR(COALESCE(NEW."DateSubmitted", CURRENT_TIMESTAMP), 'YYYYMMDD')
            || '-' || COALESCE(s."StudentNumber", NEW."StudentID"::TEXT)
            || '-' || COALESCE(m."ModuleCode", NEW."ListingID"::TEXT)
        INTO NEW."Reference"
        FROM (VALUES (NEW."StudentID", NEW."ListingID")) AS input("StudentID", "ListingID")
        LEFT JOIN "STUDENT" s
          ON s."StudentID" = input."StudentID"
        LEFT JOIN "DEMI_LISTING" l
          ON l."ListingID" = input."ListingID"
        LEFT JOIN "NWU_MODULE" m
          ON m."ModuleID" = l."ModuleID";
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_generate_demi_application_reference
BEFORE INSERT OR UPDATE OF "StudentID", "ListingID", "DateSubmitted", "Reference"
ON "DEMI_APPLICATION"
FOR EACH ROW
EXECUTE FUNCTION generate_demi_application_reference();

-- 17. CREATE ACTIVE DEMI POSITION APPOINTMENT TABLE (P&C122F SECTION G ALIGNED)
CREATE TABLE "DEMI_POSITION" (
    "PositionID" INT GENERATED BY DEFAULT AS IDENTITY,
    "ApplicationID" INT NOT NULL,
    "PaymentScaleID" INT NOT NULL,
    "TempBudgetPositionNo" VARCHAR(30),
    "AccountingCombination" VARCHAR(30),
    "TotalAllocatedHours" NUMERIC(5, 2) DEFAULT 0.00,
    "PositionStatus" VARCHAR(30) DEFAULT 'Pending Admin Review',
    "StartDate" TIMESTAMPTZ,
    "TerminationDate" TIMESTAMPTZ,
    "AdminComment" TEXT,
    CONSTRAINT "PK_DEMI_POSITION" PRIMARY KEY ("PositionID"),
    CONSTRAINT "FK_DEMI_POSITION_DEMI_APPLICATION" FOREIGN KEY ("ApplicationID") 
        REFERENCES "DEMI_APPLICATION" ("ApplicationID") ON DELETE CASCADE,
    CONSTRAINT "CHK_DEMI_POSITION_Status" CHECK (
        "PositionStatus" IN ('Pending Admin Review', 'Approved', 'Rejected', 'Returned')
    )
);

CREATE TABLE "RESPONSIBILITY" (
    "ResponsibilityID" INT GENERATED BY DEFAULT AS IDENTITY,
    "PositionID" INT NOT NULL,
    "Description" TEXT NOT NULL,
    CONSTRAINT "PK_RESPONSIBILITY" PRIMARY KEY ("ResponsibilityID"),
    CONSTRAINT "FK_RESPONSIBILITY_DEMI_POSITION" FOREIGN KEY ("PositionID") 
        REFERENCES "DEMI_POSITION" ("PositionID") ON DELETE CASCADE
);

-- 18. CREATE WORK SESSION TIMESHEET TABLE (P&C132F ALIGNED)
CREATE TABLE "WORK_SESSION" (
    "SessionID" INT GENERATED BY DEFAULT AS IDENTITY,
    "PositionID" int NOT NULL,
    "ActivityDescription" varchar(200),
    "StartTime" timestamptz NOT NULL,
    "EndTime" timestamptz,
    "TotalHoursWorked" decimal(5,2),
    "EstimatedRemuneration" decimal(8,2),
    "LecturerApproval" boolean DEFAULT false,
    CONSTRAINT "PK_WORK_SESSION" PRIMARY KEY ("SessionID"),
    CONSTRAINT "FK_WORK_SESSION_DEMI_POSITION" FOREIGN KEY ("PositionID") REFERENCES "DEMI_POSITION" ("PositionID") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

-- 19. CREATE REMUNERATION CLAIM TABLE (P&C132F ALIGNED)
CREATE TABLE "REMUNERATION_CLAIM" (
    "ClaimID" INT GENERATED BY DEFAULT AS IDENTITY,
    "ClaimReferenceNumber" varchar(50) NOT NULL,
    "ApplicationID" int NOT NULL,
    "ModuleID" int NOT NULL,
    "PeriodStartDate" date,
    "PeriodEndDate" date,
    "TotalHoursClaimed" decimal(5,2) NOT NULL,
    "TotalClaimAmount" decimal(10,2) NOT NULL,
    "HourlyRateApplied" decimal(10,2) NOT NULL,
    "ClaimStatus" varchar(20) DEFAULT 'Pending',
    "LecturerComment" TEXT,
    "SubmissionDate" timestamptz DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_REMUNERATION_CLAIM" PRIMARY KEY ("ClaimID"),
    CONSTRAINT "UQ_REMUNERATION_CLAIM_ReferenceNumber" UNIQUE ("ClaimReferenceNumber"),
    CONSTRAINT "FK_REMUNERATION_CLAIM_DEMI_APPLICATION" FOREIGN KEY ("ApplicationID") REFERENCES "DEMI_APPLICATION" ("ApplicationID") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT "FK_REMUNERATION_CLAIM_NWU_MODULE" FOREIGN KEY ("ModuleID") REFERENCES "NWU_MODULE" ("ModuleID") DEFERRABLE INITIALLY IMMEDIATE
);

-- 20. CREATE NOTIFICATION AUDIT TABLE
CREATE TABLE "NOTIFICATION" (
  "NotificationID" INT GENERATED BY DEFAULT AS IDENTITY,
  "RecipientUserID" int NOT NULL,
  "NotificationType" varchar(50) NOT NULL,
  "Subject" varchar(100),
  "Message" text NOT NULL,
  "IsRead" boolean DEFAULT false,
  "CreatedTimestamp" timestamptz DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY ("NotificationID"),
  CONSTRAINT "FK_NOTIFICATION_APP_USER"
    FOREIGN KEY ("RecipientUserID")
    REFERENCES "APP_USER" ("UserID")
    DEFERRABLE INITIALLY IMMEDIATE
);

-- COLUMN COMMENTS
COMMENT ON COLUMN "SYSTEM_ROLE"."RoleName" IS 'Student, Lecturer, Administrator';
COMMENT ON COLUMN "ORGANISATIONAL_ENTITY"."OE_Code" IS 'NWU OE Code e.g. 8412';
COMMENT ON COLUMN "NWU_MODULE"."ModuleCode" IS 'e.g., CMPG323';
COMMENT ON COLUMN "NWU_MODULE"."MinAcademicRequirement" IS 'Automated academic check threshold';
COMMENT ON COLUMN "PAYMENT_SCALE"."RoleLevel" IS 'e.g., Undergraduate Demi, Postgraduate Demi';
COMMENT ON COLUMN "APP_USER"."Email" IS 'University credentials for login';
COMMENT ON COLUMN "APP_USER"."PasswordHash" IS 'Password hashed with Bcrypt';
COMMENT ON COLUMN "STUDENT"."AccountType" IS 'Savings or Cheque';
COMMENT ON COLUMN "SUPPORTING_DOCUMENT"."DocumentType" IS 'Academic Transcript, Certified ID, Bank Letter, etc.';
COMMENT ON COLUMN "SECURITY_TOKEN"."JWT_Token" IS 'Session authentication token';
COMMENT ON COLUMN "DEMI_APPLICATION"."ApplicationStatus" IS 'Pending, In Review, Approved, Rejected';
COMMENT ON COLUMN "DEMI_APPLICATION"."VerificationEligibilityStatus" IS 'Automated result check';
COMMENT ON COLUMN "WORK_SESSION"."TotalHoursWorked" IS 'Duration calculated upon clock-out';
COMMENT ON COLUMN "WORK_SESSION"."LecturerApproval" IS 'Session verification';
COMMENT ON COLUMN "REMUNERATION_CLAIM"."ClaimStatus" IS 'Pending, Under Review, Verified';
COMMENT ON COLUMN "NOTIFICATION"."NotificationType" IS 'Application Update, Claim Submission, etc.';

-- ============================================================================
-- DACMS SEED DATA SCRIPT 
-- Target Platform: PostgreSQL
-- ============================================================================

BEGIN;

-- 1. Insert System Roles
INSERT INTO "SYSTEM_ROLE" ("RoleName") VALUES 
('Student'), 
('Lecturer'), 
('Administrator');

-- 2. Insert Organisational Entities (NWU Schools / OE Codes)
INSERT INTO "ORGANISATIONAL_ENTITY" ("OE_Code", "OEName", "FacultyName") VALUES 
('8412', 'School of Computer Science and Information Systems', 'Faculty of Natural & Agricultural Sciences'),
('8413', 'School of Electrical, Electronic and Computer Engineering', 'Faculty of Engineering'),
('8414', 'School of Mechanical Engineering', 'Faculty of Engineering'),
('8415', 'School of Chemical Engineering', 'Faculty of Engineering');

-- 3. Insert Payment Scales (Official NWU Hourly Tariffs 2026)
INSERT INTO "PAYMENT_SCALE" ("RoleLevel", "StandardHourlyRate", "EffectiveYear") VALUES 
('Undergraduate Demi', 86.75, 2026), 
('Postgraduate Demi', 107.80, 2026);

-- 4. Insert Academic Modules (Linked to OE_ID)
INSERT INTO "NWU_MODULE" ("ModuleCode", "ModuleName", "Description", "MinAcademicRequirement", "OE_ID") VALUES 
('CMPG323', 'IT Developments', 'Practical software engineering and deployment.', 65.00, 1),
('CMPG311', 'Databases', 'Relational design and advanced SQL querying.', 65.00, 1),
('INGM311', 'Engineering Thermodynamics', 'Advanced thermal systems and cycle analyses.', 60.00, 3),
('EERI124', 'Introduction to Digital Systems', 'Fundamental logic design and gates.', 65.00, 2),
('REES211', 'Renewable Energy Systems', 'Clean energy grid systems and power.', 60.00, 4),
('CMPG221', 'Data Structures', 'Algorithms and memory organisation.', 65.00, 1),
('INGM121', 'Engineering Statics', 'Rigid body mechanics and forces.', 60.00, 3),
('INGM222', 'Engineering Dynamics', 'Motion, kinetic energy, and accelerations.', 60.00, 3),
('INGM412', 'Fluid Mechanics', 'Incompressible flow and piping design.', 60.00, 4),
('EERI223', 'Signal Processing', 'Analogue and digital waves analyses.', 65.00, 2);

-- 5. Insert App Users (22 Students [RoleID=1], 4 Lecturers [RoleID=2], 2 Admins [RoleID=3])
INSERT INTO "APP_USER" ("FName", "LName", "Email", "PasswordHash", "RoleID") VALUES 
('Sipho', 'Ndlovu', 'sipho.ndlovu@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1),   -- UserID: 1
('Pieter', 'Botha', 'pieter.botha@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1),  -- UserID: 2
('Lerato', 'Mokoena', 'lerato.mokoena@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1),-- UserID: 3
('Sanele', 'Khumalo', 'sanele.khumalo@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1),-- UserID: 4
('Fatima', 'Patel', 'fatima.patel@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1),   -- UserID: 5
('Johan', 'Coetzee', 'johan.coetzee@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1), -- UserID: 6
('Zola', 'Dlamini', 'zola.dlamini@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1),   -- UserID: 7
('Chen', 'Wei', 'chen.wei@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1),        -- UserID: 8
('Ananya', 'Naidoo', 'ananya.naidoo@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1), -- UserID: 9
('David', 'Miller', 'david.miller@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1), -- UserID: 10
('Alan', 'Smith', 'alan.smith@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 2),    -- UserID: 11
('Beatrice', 'Jones', 'beatrice.jones@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 2),-- UserID: 12
('Charles', 'Brown', 'charles.brown@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 2),  -- UserID: 13
('Diane', 'Taylor', 'diane.taylor@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 2),  -- UserID: 14
('Eric', 'Johnson', 'eric.johnson@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 3),  -- UserID: 15
('Fiona', 'Carter', 'fiona.carter@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 3);  -- UserID: 16

INSERT INTO "APP_USER" ("FName", "LName", "Email", "PasswordHash", "RoleID") VALUES
('Naledi', 'Molefe', 'naledi.molefe@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1), -- UserID: 17
('Thabo', 'Maseko', 'thabo.maseko@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1), -- UserID: 18
('Amara', 'Pillay', 'amara.pillay@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1), -- UserID: 19
('Kagiso', 'Mokoena', 'kagiso.mokoena@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1), -- UserID: 20
('Elize', 'van der Merwe', 'elize.vandermerwe@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1), -- UserID: 21
('Musa', 'Dube', 'musa.dube@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1), -- UserID: 22
('Ayesha', 'Khan', 'ayesha.khan@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1), -- UserID: 23
('Bokang', 'Seakamela', 'bokang.seakamela@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1), -- UserID: 24
('Liam', 'Jacobs', 'liam.jacobs@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1), -- UserID: 25
('Rethabile', 'Mahlangu', 'rethabile.mahlangu@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1), -- UserID: 26
('Mia', 'Botha', 'mia.botha@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1), -- UserID: 27
('Andile', 'Nkosi', 'andile.nkosi@nwu.ac.za', '$2a$12$nXX6SA.o/DsXSzbN7i.6IuZyhv9U.WxXUUnr7OIOcqIYIZiprIj.C', 1); -- UserID: 28

-- 6. Insert Subtype Entities (1:1 with APP_USER PKs)
INSERT INTO "STUDENT" ("StudentID", "StudentNumber", "StudyLevel", "ID_PassportNumber", "Title", "Gender", "DateOfBirth", "IncomeTaxNumber", "SACitizen", "ResidentialAddress", "PostalAddress", "NextOfKinName", "NextOfKinMobile", "HighestQualification", "ContactDetails", "BankName", "AccountNumber", "AccountType", "BranchCode", "AccountHolderName") VALUES 
(1, '12345678', 'Undergraduate', '0203155123081', 'Mr', 'Male', '2002-03-15', '9012345678', TRUE, '12 University Way, Potchefstroom', 'P.O. Box 100, Potchefstroom', 'Nomvula Ndlovu', '+27829990001', 'BSc CS Progress', '+27820000001', 'FNB', '62111111111', 'Savings', '250655', 'Sipho Ndlovu'),
(2, '23456789', 'Undergraduate', '0111205123082', 'Mr', 'Male', '2001-11-20', '9012345679', TRUE, '45 Hoffman St, Potchefstroom', '45 Hoffman St, Potchefstroom', 'Jan Botha', '+27829990002', 'BSc IT Progress', '+27820000002', 'Standard Bank', '10111111112', 'Cheque', '051001', 'Pieter Botha'),
(3, '34567890', 'Postgraduate', '9905125123083', 'Ms', 'Female', '1999-05-12', '9012345680', TRUE, '88 Borcherd St, Potchefstroom', 'P.O. Box 202, Potchefstroom', 'Thabo Mokoena', '+27829990003', 'BSc Honours in Computer Science', '+27820000003', 'Nedbank', '19811111113', 'Savings', '198765', 'Lerato Mokoena'),
(4, '45678901', 'Undergraduate', '0308225123084', 'Mr', 'Male', '2003-08-22', '9012345681', TRUE, '15 Campus Heights, Potchefstroom', '15 Campus Heights, Potchefstroom', 'Bongani Khumalo', '+27829990004', 'BEng Progress', '+27820000004', 'Capitec', '15211111114', 'Savings', '470010', 'Sanele Khumalo'),
(5, '56789012', 'Postgraduate', '9801015123085', 'Ms', 'Female', '1998-01-01', '9012345682', TRUE, '99 Malherbe St, Potchefstroom', 'P.O. Box 305, Potchefstroom', 'Aisha Patel', '+27829990005', 'BEng Honours in Chemical Eng', '+27820000005', 'ABSA', '40511111115', 'Cheque', '632005', 'Fatima Patel'),
(6, '67890123', 'Undergraduate', '0209105123086', 'Mr', 'Male', '2002-09-10', '9012345683', TRUE, '33 Steve Biko Ave, Potchefstroom', '33 Steve Biko Ave, Potchefstroom', 'Kobus Coetzee', '+27829990006', 'BSc CS Progress', '+27820000006', 'FNB', '62111111116', 'Savings', '250655', 'Johan Coetzee'),
(7, '78901234', 'Postgraduate', '9912045123087', 'Ms', 'Female', '1999-12-04', '9012345684', TRUE, '12 Meyer St, Potchefstroom', 'P.O. Box 102, Potchefstroom', 'Sbusiso Dlamini', '+27829990007', 'BEng Honours in Mech Eng', '+27820000007', 'Standard Bank', '10111111117', 'Cheque', '051001', 'Zola Dlamini'),
(8, '89012345', 'Undergraduate', '0304055123088', 'Mr', 'Male', '2003-04-05', '9012345685', TRUE, '77 Molen St, Potchefstroom', '77 Molen St, Potchefstroom', 'Li Wei', '+27829990008', 'BSc IT Progress', '+27820000008', 'Nedbank', '19811111118', 'Savings', '198765', 'Chen Wei'),
(9, '90123456', 'Postgraduate', '9807185123089', 'Ms', 'Female', '1998-07-18', '9012345686', TRUE, '21 Esselen St, Potchefstroom', 'P.O. Box 550, Potchefstroom', 'Kovash Naidoo', '+27829990009', 'BEng Honours in Chem Eng', '+27820000009', 'Capitec', '15211111119', 'Savings', '470010', 'Ananya Naidoo'),
(10, '91234567', 'Undergraduate', '0202025123090', 'Mr', 'Male', '2002-02-02', '9012345687', TRUE, '101 President St, Potchefstroom', '101 President St, Potchefstroom', 'Sarah Miller', '+27829990010', 'BEng Progress', '+27820000010', 'ABSA', '40511111120', 'Savings', '632005', 'David Miller');

INSERT INTO "STUDENT" ("StudentID", "StudentNumber", "StudyLevel", "ContactDetails", "BankName", "AccountNumber", "BranchCode", "AccountHolderName", "ResidentialAddress", "PostalAddress", "HighestQualification") VALUES
(17, '22345671', 'Undergraduate', '+27820000017', 'FNB', '00000000017', '250655', 'Naledi Molefe', 'Potchefstroom campus residence', 'NWU Potchefstroom campus', 'BSc Computer Science in progress'),
(18, '22345672', 'Undergraduate', '+27820000018', 'Capitec', '00000000018', '470010', 'Thabo Maseko', 'Miederpark, Potchefstroom', 'Miederpark, Potchefstroom', 'BSc Information Technology in progress'),
(19, '22345673', 'Postgraduate', '+27820000019', 'Nedbank', '00000000019', '198765', 'Amara Pillay', 'Potchefstroom campus residence', 'NWU Potchefstroom campus', 'BSc Honours Computer Science'),
(20, '22345674', 'Undergraduate', '+27820000020', 'ABSA', '00000000020', '632005', 'Kagiso Mokoena', 'Ikageng, Potchefstroom', 'Ikageng, Potchefstroom', 'BEng Mechanical Engineering in progress'),
(21, '22345675', 'Undergraduate', '+27820000021', 'Standard Bank', '00000000021', '051001', 'Elize van der Merwe', 'Potchefstroom campus residence', 'NWU Potchefstroom campus', 'BEng Electrical Engineering in progress'),
(22, '22345676', 'Postgraduate', '+27820000022', 'FNB', '00000000022', '250655', 'Musa Dube', 'Baillie Park, Potchefstroom', 'Baillie Park, Potchefstroom', 'BSc Honours Renewable Energy'),
(23, '22345677', 'Undergraduate', '+27820000023', 'Capitec', '00000000023', '470010', 'Ayesha Khan', 'Potchefstroom campus residence', 'NWU Potchefstroom campus', 'BSc Computer Science in progress'),
(24, '22345678', 'Undergraduate', '+27820000024', 'Nedbank', '00000000024', '198765', 'Bokang Seakamela', 'Dassierand, Potchefstroom', 'Dassierand, Potchefstroom', 'BEng Mechanical Engineering in progress'),
(25, '22345679', 'Undergraduate', '+27820000025', 'ABSA', '00000000025', '632005', 'Liam Jacobs', 'Potchefstroom campus residence', 'NWU Potchefstroom campus', 'BSc Information Technology in progress'),
(26, '22345680', 'Postgraduate', '+27820000026', 'Standard Bank', '00000000026', '051001', 'Rethabile Mahlangu', 'Miederpark, Potchefstroom', 'Miederpark, Potchefstroom', 'BEng Honours Chemical Engineering'),
(27, '22345681', 'Undergraduate', '+27820000027', 'FNB', '00000000027', '250655', 'Mia Botha', 'Potchefstroom campus residence', 'NWU Potchefstroom campus', 'BSc Information Technology in progress'),
(28, '22345682', 'Postgraduate', '+27820000028', 'Capitec', '00000000028', '470010', 'Andile Nkosi', 'Potchefstroom campus residence', 'NWU Potchefstroom campus', 'BEng Honours Mechanical Engineering');

INSERT INTO "LECTURER" ("LecturerID", "Department", "OE_ID") VALUES 
(11, 'School of Computer Science and Information Systems', 1),
(12, 'School of Electrical, Electronic and Computer Engineering', 2),
(13, 'School of Mechanical Engineering', 3),
(14, 'School of Chemical Engineering', 4);

INSERT INTO "ADMINISTRATOR" ("AdminID", "TFASecret", "TFABackupCodes", "TFALastStep", "TFAConfirmedAt", "BudgetAllocationRights") VALUES
(15, NULL, '{}', NULL, NULL, TRUE),
(16, NULL, '{}', NULL, NULL, TRUE);

-- 7. Insert Supporting Documents
INSERT INTO "SUPPORTING_DOCUMENT" ("StudentID", "DocumentType", "FilePath", "UploadTimestamp") VALUES 
(1, 'Academic Transcript', '/app/documents/exampleDoc.jpg', '2026-08-01 09:00:00+02'),
(1, 'Bank Confirmation', '/app/documents/exampleDoc.jpg', '2026-08-01 09:15:00+02'),
(2, 'Academic Transcript', '/app/documents/exampleDoc.jpg', '2026-08-02 10:00:00+02'),
(2, 'Certified ID', '/app/documents/exampleDoc.jpg', '2026-08-02 10:10:00+02'),
(3, 'Academic Transcript', '/app/documents/testPDF.pdf', '2026-08-03 11:00:00+02'),
(4, 'Academic Transcript', '/app/documents/exampleDoc.jpg', '2026-08-04 12:00:00+02'),
(5, 'Academic Transcript', '/app/documents/exampleDoc.jpg', '2026-08-05 13:00:00+02'),
(6, 'Academic Transcript', '/app/documents/exampleDoc.jpg', '2026-08-06 14:00:00+02'),
(7, 'Academic Transcript', '/app/documents/exampleDoc.jpg', '2026-08-07 15:00:00+02'),
(8, 'Academic Transcript', '/app/documents/exampleDoc.jpg', '2026-08-08 16:00:00+02'),
(9, 'Academic Transcript', '/app/documents/exampleDoc.jpg', '2026-08-09 17:00:00+02'),
(10, 'Academic Transcript', '/app/documents/exampleDoc.jpg', '2026-08-10 18:00:00+02');

INSERT INTO "SUPPORTING_DOCUMENT" ("StudentID", "DocumentType", "FilePath", "UploadTimestamp") VALUES
(17, 'Academic Transcript', '/app/documents/demo/naledi-transcript.pdf', '2026-09-28 09:10:00+02'),
(17, 'Bank Confirmation', '/app/documents/demo/naledi-bank-letter.pdf', '2026-09-28 09:18:00+02'),
(18, 'Academic Transcript', '/app/documents/demo/thabo-transcript.pdf', '2026-09-29 11:20:00+02'),
(19, 'Academic Transcript', '/app/documents/demo/amara-transcript.pdf', '2026-09-30 08:45:00+02'),
(19, 'Certified ID', '/app/documents/demo/amara-id.pdf', '2026-09-30 08:52:00+02'),
(20, 'Academic Transcript', '/app/documents/demo/kagiso-transcript.pdf', '2026-10-01 13:05:00+02'),
(21, 'Academic Transcript', '/app/documents/demo/elize-transcript.pdf', '2026-10-01 14:30:00+02'),
(22, 'Academic Transcript', '/app/documents/demo/musa-transcript.pdf', '2026-10-02 10:12:00+02'),
(23, 'Academic Transcript', '/app/documents/demo/ayesha-transcript.pdf', '2026-10-02 15:42:00+02'),
(24, 'Academic Transcript', '/app/documents/demo/bokang-transcript.pdf', '2026-10-03 09:25:00+02'),
(24, 'Bank Confirmation', '/app/documents/demo/bokang-bank-letter.pdf', '2026-10-03 09:31:00+02'),
(25, 'Academic Transcript', '/app/documents/demo/liam-transcript.pdf', '2026-10-04 12:14:00+02'),
(26, 'Academic Transcript', '/app/documents/demo/rethabile-transcript.pdf', '2026-10-05 08:58:00+02'),
(27, 'Academic Transcript', '/app/documents/demo/mia-transcript.pdf', '2026-10-05 16:22:00+02'),
(28, 'Academic Transcript', '/app/documents/demo/andile-transcript.pdf', '2026-10-06 10:40:00+02');

-- 8. Insert Lecturer Module Mapping
INSERT INTO "LECTURER_MODULE" ("LecturerID", "ModuleID") VALUES 
(11, 1), -- Alan: CMPG323
(11, 2), -- Alan: CMPG311
(11, 6), -- Alan: CMPG221
(12, 4), -- Beatrice: EERI124
(12, 10),-- Beatrice: EERI223
(13, 3), -- Charles: INGM311
(13, 7), -- Charles: INGM121
(13, 8), -- Charles: INGM222
(14, 5), -- Diane: REES211
(14, 9); -- Diane: INGM412

-- 9. Insert Module Budgets
INSERT INTO "MODULE_BUDGET" ("ModuleID", "LecturerID", "AllocatedBudget", "CurrentBudgetUsage", "MaxAllowableWorkHours", "AcademicYear") VALUES 
(1, 11, 17292.96, 1641.88, 160, 2026),
(2, 11, 13880.00, 607.25, 160, 2026),
(3, 13, 17592.96, 646.80, 160, 2026),
(4, 12, 13880.00, 0.00, 160, 2026),
(5, 14, 10780.00, 431.20, 100, 2026),
(6, 11, 13880.00, 0.00, 160, 2026),
(7, 13, 13272.75, 0.00, 150, 2026),
(8, 13, 7078.80, 260.25, 80, 2026),
(9, 14, 4398.24, 215.60, 40, 2026),
(10, 12, 10995.60, 0.00, 100, 2026);

-- 10. Insert Student Module Grades
INSERT INTO "STUDENT_MODULE_GRADE" ("StudentID", "ModuleID", "GradeAchieved") VALUES 
(1, 1, 74.50),
(2, 2, 81.00),
(3, 1, 85.00),
(4, 4, 70.00),
(5, 5, 88.50),
(6, 6, 68.00),
(7, 3, 77.00),
(8, 7, 72.00),
(9, 9, 83.00),
(10, 8, 79.50);

INSERT INTO "STUDENT_MODULE_GRADE" ("StudentID", "ModuleID", "GradeAchieved") VALUES
(17, 1, 83.00), (17, 2, 74.00), (17, 6, 77.50),
(18, 1, 78.00), (18, 6, 71.00),
(19, 2, 89.00), (19, 1, 81.00), (19, 6, 86.00),
(20, 3, 72.00), (20, 7, 66.00),
(21, 4, 69.00), (21, 10, 73.00),
(22, 5, 86.00), (22, 1, 80.00),
(23, 6, 58.00), (23, 1, 62.00),
(24, 7, 73.00), (24, 3, 68.00),
(25, 8, 68.00), (25, 6, 75.00),
(26, 9, 83.00), (26, 5, 79.00),
(27, 10, 76.00), (27, 4, 72.00),
(28, 9, 79.00), (28, 3, 82.00);

-- 11. Insert Demi Listings
INSERT INTO "DEMI_LISTING" ("ModuleID", "LecturerID", "Deadline", "MinimumGrade") VALUES 
(1, 11, '2026-10-15 23:59:59+02', 65.00),
(2, 11, '2026-10-15 23:59:59+02', 65.00),
(3, 13, '2026-10-15 23:59:59+02', 60.00),
(4, 12, '2026-10-15 23:59:59+02', 65.00),
(5, 14, '2026-10-15 23:59:59+02', 60.00),
(6, 11, '2026-10-15 23:59:59+02', 65.00),
(7, 13, '2026-10-15 23:59:59+02', 60.00),
(8, 13, '2026-10-15 23:59:59+02', 60.00),
(9, 14, '2026-10-15 23:59:59+02', 60.00),
(10, 12, '2026-10-15 23:59:59+02', 65.00);

INSERT INTO "DEMI_LISTING" ("ModuleID", "LecturerID", "Deadline", "MinimumGrade") VALUES
(1, 11, '2026-10-20 23:59:59+02', 65.00), -- ListingID: 11, CMPG323 practical support
(2, 11, '2026-10-20 23:59:59+02', 65.00), -- ListingID: 12, CMPG311 database labs
(3, 13, '2026-10-22 23:59:59+02', 60.00), -- ListingID: 13, INGM311 tutorials
(4, 12, '2026-10-22 23:59:59+02', 65.00), -- ListingID: 14, EERI124 lab support
(5, 14, '2026-10-25 23:59:59+02', 60.00), -- ListingID: 15, REES211 project support
(6, 11, '2026-10-25 23:59:59+02', 65.00), -- ListingID: 16, CMPG221 programming labs
(7, 13, '2026-10-27 23:59:59+02', 60.00), -- ListingID: 17, INGM121 tutorials
(8, 13, '2026-10-27 23:59:59+02', 60.00), -- ListingID: 18, INGM222 tutorials
(9, 14, '2026-10-30 23:59:59+02', 60.00), -- ListingID: 19, INGM412 lab support
(10, 12, '2026-10-30 23:59:59+02', 65.00); -- ListingID: 20, EERI223 practicals

-- 12. Insert Applications
INSERT INTO "DEMI_APPLICATION" ("StudentID", "ListingID", "ApplicationStatus", "VerificationEligibilityStatus", "DateSubmitted", "AppReason", "ReviewComment") VALUES 
(1, 1, 'Approved', 'Eligible', '2026-08-01 10:00:00+02', 'Meets eligibility requirements', NULL),   -- ApplicationID: 1
(2, 2, 'Approved', 'Eligible', '2026-08-02 11:30:00+02', 'Meets eligibility requirements', NULL),   -- ApplicationID: 2
(3, 1, 'Approved', 'Eligible', '2026-08-03 09:15:00+02', 'Meets eligibility requirements', NULL),   -- ApplicationID: 3
(4, 4, 'In Review', 'Eligible', '2026-08-04 14:00:00+02', 'Application is under review', NULL),      -- ApplicationID: 4
(5, 5, 'Approved', 'Eligible', '2026-08-05 15:45:00+02', 'Meets eligibility requirements', NULL),   -- ApplicationID: 5
(6, 6, 'Pending', 'Eligible', '2026-08-06 08:30:00+02', 'Awaiting application review', NULL),        -- ApplicationID: 6
(7, 3, 'Approved', 'Eligible', '2026-08-07 12:10:00+02', 'Meets eligibility requirements', NULL),   -- ApplicationID: 7
(8, 7, 'Pending', 'Eligible', '2026-08-08 16:20:00+02', 'Awaiting application review', NULL),        -- ApplicationID: 8
(9, 9, 'Approved', 'Eligible', '2026-08-09 11:00:00+02', 'Meets eligibility requirements', NULL),   -- ApplicationID: 9
(10, 8, 'Approved', 'Eligible', '2026-08-10 13:25:00+02', 'Meets eligibility requirements', NULL);  -- ApplicationID: 10

INSERT INTO "DEMI_APPLICATION" ("StudentID", "ListingID", "ApplicationStatus", "VerificationEligibilityStatus", "DateSubmitted", "AppReason", "ReviewComment") VALUES
(17, 11, 'Approved', 'Eligible', '2026-10-01 08:42:00+02', 'Interested in supporting first-year programming practicals.', 'Strong CMPG323 result; appointment paperwork received.'),
(18, 11, 'In Review', 'Eligible', '2026-10-01 10:15:00+02', 'Enjoy helping peers debug Java assignments.', 'Lecturer review in progress.'),
(19, 12, 'Approved', 'Eligible', '2026-10-01 14:25:00+02', 'Interested in database design and SQL tutoring.', 'Available for weekly lab sessions.'),
(20, 13, 'Approved', 'Eligible', '2026-10-02 09:05:00+02', 'Would like to assist with thermodynamics tutorials.', 'Timetable confirmed with the lecturer.'),
(21, 14, 'Pending', 'Eligible', '2026-10-02 11:48:00+02', 'Previous experience assembling digital logic circuits.', NULL),
(22, 15, 'Approved', 'Eligible', '2026-10-02 16:12:00+02', 'Honours research aligns with renewable energy projects.', 'Appointment awaiting administrator review.'),
(23, 16, 'Rejected', 'Ineligible', '2026-10-03 08:55:00+02', 'Interested in helping with data structures labs.', 'Minimum academic requirement not met.'),
(24, 17, 'Returned', 'Eligible', '2026-10-03 12:20:00+02', 'Can support first-year statics tutorials and marking.', 'Please upload the missing bank confirmation.'),
(25, 18, 'Pending', 'Eligible', '2026-10-04 09:32:00+02', 'Enjoy explaining motion and engineering problem-solving.', NULL),
(26, 19, 'Approved', 'Eligible', '2026-10-05 08:17:00+02', 'Interested in laboratory demonstrations and report feedback.', 'Appointment approved for the remainder of the semester.'),
(27, 20, 'Approved', 'Eligible', '2026-10-05 13:40:00+02', 'Signal processing practicals complement current studies.', 'Appointment paperwork received.'),
(28, 13, 'Approved', 'Eligible', '2026-10-06 09:10:00+02', 'Can assist with tutorial preparation and problem sessions.', 'Available on Tuesday and Thursday afternoons.'),
(17, 16, 'Approved', 'Eligible', '2026-10-06 14:35:00+02', 'Also interested in supporting CMPG221 programming labs.', 'Second module appointment approved.'),
(20, 14, 'In Review', 'Eligible', '2026-10-07 08:25:00+02', 'Interested in assisting with EERI124 circuit lab demonstrations.', 'Checking timetable availability.'),
(22, 19, 'Pending', 'Eligible', '2026-10-07 10:05:00+02', 'Can help students interpret fluid mechanics lab results.', NULL);

-- 13. Insert Active Positions (Linked to Approved Applications)
-- ScaleID 1 = UG (86.75), ScaleID 2 = PG (107.80)
INSERT INTO "DEMI_POSITION" ("ApplicationID", "PaymentScaleID", "TempBudgetPositionNo", "AccountingCombination", "TotalAllocatedHours", "StartDate", "TerminationDate") VALUES 
(1, 1, 'TBF-2026-001', '8412-4101-2104', 160, '2026-07-01 00:00:00+02', '2026-11-30 23:59:59+02'), -- PositionID 1: Student 1 (UG)
(2, 1, 'TBF-2026-002', '8413-4101-2104', 160, '2026-07-01 00:00:00+02', '2026-11-30 23:59:59+02'), -- PositionID 2: Student 2 (UG)
(3, 2, 'TBF-2026-003', '8412-4101-2104', 160, '2026-07-01 00:00:00+02', '2026-11-30 23:59:59+02'), -- PositionID 3: Student 3 (PG)
(5, 2, 'TBF-2026-004', '8415-4101-2104', 100, '2026-07-01 00:00:00+02', '2026-11-30 23:59:59+02'), -- PositionID 4: Student 5 (PG)
(7, 2, 'TBF-2026-005', '8414-4101-2104', 160, '2026-07-01 00:00:00+02', '2026-11-30 23:59:59+02'), -- PositionID 5: Student 7 (PG)
(9, 2, 'TBF-2026-006', '8415-4101-2104', 40,  '2026-07-01 00:00:00+02', '2026-11-30 23:59:59+02'), -- PositionID 6: Student 9 (PG)
(10, 1, 'TBF-2026-007', '8414-4101-2104', 80,  '2026-07-01 00:00:00+02', '2026-11-30 23:59:59+02'); -- PositionID 7: Student 10 (UG)

INSERT INTO "DEMI_POSITION" ("ApplicationID", "PaymentScaleID", "TempBudgetPositionNo", "AccountingCombination", "TotalAllocatedHours", "PositionStatus", "StartDate", "TerminationDate", "AdminComment") VALUES
(11, 1, 'TBF-2026-008', '8412-4101-2104', 120, 'Approved', '2026-10-01 00:00:00+02', '2026-11-30 23:59:59+02', 'Appointment confirmed for CMPG323 labs.'),
(13, 2, 'TBF-2026-009', '8412-4101-2104', 100, 'Approved', '2026-10-01 00:00:00+02', '2026-11-30 23:59:59+02', 'Database lab and consultation support.'),
(14, 1, 'TBF-2026-010', '8414-4101-2104', 80, 'Approved', '2026-10-02 00:00:00+02', '2026-11-30 23:59:59+02', 'Thermodynamics tutorials and marking.'),
(16, 2, 'TBF-2026-011', '8415-4101-2104', 90, 'Pending Admin Review', '2026-10-02 00:00:00+02', '2026-11-30 23:59:59+02', 'Awaiting final position number.'),
(20, 2, 'TBF-2026-012', '8415-4101-2104', 100, 'Approved', '2026-10-05 00:00:00+02', '2026-11-30 23:59:59+02', 'Laboratory support appointment.'),
(21, 1, 'TBF-2026-013', '8413-4101-2104', 80, 'Approved', '2026-10-05 00:00:00+02', '2026-11-30 23:59:59+02', 'Signal processing practical assistance.'),
(22, 2, 'TBF-2026-014', '8414-4101-2104', 100, 'Approved', '2026-10-06 00:00:00+02', '2026-11-30 23:59:59+02', 'Tutorial preparation and student consultations.'),
(23, 1, 'TBF-2026-015', '8412-4101-2104', 80, 'Approved', '2026-10-06 00:00:00+02', '2026-11-30 23:59:59+02', 'Additional programming lab appointment.');

-- 14. Insert Work Sessions (Linked to PositionID FK)
INSERT INTO "WORK_SESSION" ("PositionID", "ActivityDescription", "StartTime", "EndTime", "TotalHoursWorked", "EstimatedRemuneration", "LecturerApproval") VALUES 
(1, 'Practical Lab Assistance - CMPG323', '2026-08-10 08:00:00+02', '2026-08-10 12:00:00+02', 4.00, 347.00, TRUE),  -- Sipho (UG @ 86.75)
(1, 'Assignment 1 Marking - CMPG323', '2026-08-12 09:00:00+02', '2026-08-12 11:30:00+02', 2.50, 216.88, TRUE),  -- Sipho
(2, 'Lab Setup - EERI124', '2026-08-10 14:00:00+02', '2026-08-10 18:00:00+02', 4.00, 347.00, TRUE),  -- Pieter (UG @ 86.75)
(2, 'Tutoring Session 1 - EERI124', '2026-08-11 14:00:00+02', '2026-08-11 17:00:00+02', 3.00, 260.25, TRUE),  -- Pieter
(3, 'Guest Lecture Support & Marking - CMPG323', '2026-08-10 08:00:00+02', '2026-08-10 13:00:00+02', 5.00, 539.00, TRUE),  -- Lerato (PG @ 107.80)
(3, 'Project Consultation - CMPG323', '2026-08-11 08:00:00+02', '2026-08-11 13:00:00+02', 5.00, 539.00, TRUE),  -- Lerato
(4, 'Lab Assistance - REES211', '2026-08-15 09:00:00+02', '2026-08-15 13:00:00+02', 4.00, 431.20, TRUE),  -- Fatima (PG @ 107.80)
(5, 'Thermodynamics Lab Invigilation - INGM311', '2026-08-18 09:00:00+02', '2026-08-18 15:00:00+02', 6.00, 646.80, TRUE),  -- Zola (PG @ 107.80)
(6, 'Fluid Mechanics Lab Assistance - INGM412', '2026-08-20 10:00:00+02', '2026-08-20 12:00:00+02', 2.00, 215.60, TRUE),  -- Ananya (PG @ 107.80)
(7, 'Dynamics Tutorial Session - INGM222', '2026-08-22 13:00:00+02', '2026-08-22 16:00:00+02', 3.00, 260.25, TRUE);  -- David (UG @ 86.75)

INSERT INTO "WORK_SESSION" ("PositionID", "ActivityDescription", "StartTime", "EndTime", "TotalHoursWorked", "EstimatedRemuneration", "LecturerApproval") VALUES
(8, 'CMPG323 Java practical assistance and debugging clinic', '2026-10-01 09:00:00+02', '2026-10-01 12:00:00+02', 3.00, 260.25, TRUE),
(8, 'CMPG323 assignment marking and feedback', '2026-10-02 13:00:00+02', '2026-10-02 16:30:00+02', 3.50, 303.63, TRUE),
(8, 'Prepare examples for next programming practical', '2026-10-06 10:00:00+02', '2026-10-06 12:00:00+02', 2.00, 173.50, FALSE),
(9, 'CMPG311 SQL lab support and query troubleshooting', '2026-10-01 14:00:00+02', '2026-10-01 18:00:00+02', 4.00, 431.20, TRUE),
(9, 'Database design consultation hour', '2026-10-03 10:00:00+02', '2026-10-03 13:00:00+02', 3.00, 323.40, FALSE),
(10, 'INGM311 tutorial: energy balances and worked examples', '2026-10-02 09:00:00+02', '2026-10-02 12:00:00+02', 3.00, 260.25, TRUE),
(10, 'Thermodynamics assignment marking', '2026-10-06 13:00:00+02', '2026-10-06 16:00:00+02', 3.00, 260.25, FALSE),
(11, 'REES211 project consultation and literature review guidance', '2026-10-03 09:00:00+02', '2026-10-03 13:00:00+02', 4.00, 431.20, TRUE),
(11, 'Renewable energy lab equipment preparation', '2026-10-06 08:30:00+02', '2026-10-06 11:00:00+02', 2.50, 269.50, FALSE),
(12, 'INGM412 fluid flow laboratory demonstrations', '2026-10-05 09:00:00+02', '2026-10-05 13:00:00+02', 4.00, 431.20, TRUE),
(12, 'Lab report feedback and marking', '2026-10-07 09:00:00+02', '2026-10-07 12:00:00+02', 3.00, 323.40, FALSE),
(13, 'EERI223 signal processing practical setup', '2026-10-05 13:00:00+02', '2026-10-05 16:00:00+02', 3.00, 260.25, TRUE),
(13, 'Fourier transform problem session', '2026-10-07 13:00:00+02', '2026-10-07 16:00:00+02', 3.00, 260.25, FALSE),
(14, 'INGM311 tutorial preparation and student consultations', '2026-10-06 14:00:00+02', '2026-10-06 17:00:00+02', 3.00, 323.40, TRUE),
(15, 'CMPG221 data structures lab: trees and traversal', '2026-10-07 10:00:00+02', '2026-10-07 13:00:00+02', 3.00, 260.25, FALSE);

-- 15. Insert Remuneration Claims (Linked via ApplicationID and ModuleID)
INSERT INTO "REMUNERATION_CLAIM" ("ClaimReferenceNumber", "ApplicationID", "ModuleID", "PeriodStartDate", "PeriodEndDate", "TotalHoursClaimed", "TotalClaimAmount", "HourlyRateApplied", "ClaimStatus", "SubmissionDate") VALUES 
('CLAIM-2026-08-001', 1, 1, '2026-08-01', '2026-08-24', 6.50, 563.88, 86.75, 'Verified', '2026-08-25 09:00:00+02'),
('CLAIM-2026-08-002', 2, 4, '2026-08-01', '2026-08-24', 7.00, 607.25, 86.75, 'Verified', '2026-08-25 10:30:00+02'),
('CLAIM-2026-08-003', 3, 1, '2026-08-01', '2026-08-25', 10.00, 1078.00, 107.80, 'Verified', '2026-08-26 08:15:00+02'),
('CLAIM-2026-08-004', 5, 5, '2026-08-01', '2026-08-26', 4.00, 431.20, 107.80, 'Pending', '2026-08-27 14:00:00+02'),
('CLAIM-2026-08-005', 7, 3, '2026-08-01', '2026-08-27', 6.00, 646.80, 107.80, 'Under Review', '2026-08-28 11:45:00+02');

INSERT INTO "REMUNERATION_CLAIM" ("ClaimReferenceNumber", "ApplicationID", "ModuleID", "PeriodStartDate", "PeriodEndDate", "TotalHoursClaimed", "TotalClaimAmount", "HourlyRateApplied", "ClaimStatus", "LecturerComment", "SubmissionDate") VALUES
('CLAIM-2026-10-011', 11, 1, '2026-10-01', '2026-10-02', 6.50, 563.88, 86.75, 'Verified', 'Hours confirmed against the practical roster.', '2026-10-03 09:15:00+02'),
('CLAIM-2026-10-013', 13, 2, '2026-10-01', '2026-10-03', 7.00, 754.60, 107.80, 'Under Review', 'Please attach the consultation attendance sheet.', '2026-10-04 11:35:00+02'),
('CLAIM-2026-10-014', 14, 3, '2026-10-02', '2026-10-06', 6.00, 520.50, 86.75, 'Pending', NULL, '2026-10-07 08:20:00+02'),
('CLAIM-2026-10-016', 16, 5, '2026-10-03', '2026-10-06', 6.50, 700.70, 107.80, 'Verified', 'Project support approved.', '2026-10-07 10:10:00+02'),
('CLAIM-2026-10-020', 20, 9, '2026-10-05', '2026-10-07', 7.00, 754.60, 107.80, 'Under Review', 'Lab hours checked; marking still to be reviewed.', '2026-10-07 15:05:00+02'),
('CLAIM-2026-10-021', 21, 10, '2026-10-05', '2026-10-07', 6.00, 520.50, 86.75, 'Pending', NULL, '2026-10-07 16:30:00+02'),
('CLAIM-2026-10-022', 22, 3, '2026-10-06', '2026-10-06', 3.00, 323.40, 107.80, 'Pending', NULL, '2026-10-07 12:45:00+02');

-- 16. Insert Audit Notifications
INSERT INTO "NOTIFICATION" ("RecipientUserID", "NotificationType", "Subject", "Message", "IsRead", "CreatedTimestamp") VALUES 
(1, 'Application Update', 'Application Approved: CMPG323', 'Your application for CMPG323 has been approved.', TRUE, '2026-08-01 10:05:00+02'),
(2, 'Application Update', 'Application Approved: EERI124', 'Your application for EERI124 has been approved.', TRUE, '2026-08-02 11:35:00+02'),
(3, 'Application Update', 'Application Approved: CMPG323', 'Your application for CMPG323 has been approved.', TRUE, '2026-08-03 09:20:00+02'),
(4, 'Application Update', 'Application Under Review: EERI124', 'Your application for EERI124 is under lecturer review.', FALSE, '2026-08-04 14:05:00+02'),
(5, 'Application Update', 'Application Approved: REES211', 'Your application for REES211 has been approved.', TRUE, '2026-08-05 15:50:00+02'),
(6, 'Application Update', 'Application Submitted: CMPG221', 'Your application for CMPG221 was submitted successfully.', FALSE, '2026-08-06 08:35:00+02'),
(7, 'Application Update', 'Application Approved: INGM311', 'Your application for INGM311 has been approved.', TRUE, '2026-08-07 12:15:00+02'),
(8, 'Application Update', 'Application Submitted: INGM121', 'Your application for INGM121 was submitted successfully.', FALSE, '2026-08-08 16:25:00+02'),
(9, 'Application Update', 'Application Approved: INGM412', 'Your application for INGM412 has been approved.', TRUE, '2026-08-09 11:05:00+02'),
(10, 'Application Update', 'Application Approved: INGM222', 'Your application for INGM222 has been approved.', TRUE, '2026-08-10 13:30:00+02');

INSERT INTO "NOTIFICATION" ("RecipientUserID", "NotificationType", "Subject", "Message", "IsRead", "CreatedTimestamp") VALUES
(17, 'Application Update', 'Appointment approved: CMPG323', 'Your CMPG323 demi appointment is approved. Review your responsibilities and allocation in your profile.', FALSE, '2026-10-01 08:50:00+02'),
(18, 'Application Update', 'Application in review: CMPG323', 'Your CMPG323 application is with the lecturer for review.', FALSE, '2026-10-01 10:18:00+02'),
(19, 'Claim Submission', 'Claim submitted: CMPG311', 'Your October CMPG311 claim has been submitted and is awaiting lecturer review.', FALSE, '2026-10-04 11:40:00+02'),
(20, 'Application Update', 'Appointment approved: INGM311', 'Your INGM311 appointment has been approved. Please check your allocated hours.', TRUE, '2026-10-02 09:12:00+02'),
(21, 'Application Update', 'Application received: EERI124', 'Your application has been received and is awaiting review.', FALSE, '2026-10-02 11:50:00+02'),
(22, 'Application Update', 'Appointment pending administration: REES211', 'The lecturer approved your application. Your appointment is awaiting administrator review.', FALSE, '2026-10-02 16:20:00+02'),
(23, 'Application Update', 'Application outcome: CMPG221', 'Your CMPG221 application was not eligible because the minimum academic requirement was not met.', TRUE, '2026-10-03 09:05:00+02'),
(24, 'Application Update', 'Action required: INGM121', 'Please upload a bank confirmation document so the lecturer can continue reviewing your application.', FALSE, '2026-10-03 12:25:00+02'),
(25, 'Application Update', 'Application received: INGM222', 'Your application has been received and is awaiting lecturer review.', FALSE, '2026-10-04 09:35:00+02'),
(26, 'Claim Submission', 'Claim under review: INGM412', 'Your submitted claim is being checked against the laboratory timesheet.', FALSE, '2026-10-07 15:10:00+02'),
(27, 'Claim Submission', 'Claim submitted: EERI223', 'Your October EERI223 claim is awaiting lecturer review.', FALSE, '2026-10-07 16:32:00+02'),
(28, 'Application Update', 'Appointment approved: INGM311', 'Your INGM311 appointment is approved. Contact the lecturer to coordinate tutorial times.', FALSE, '2026-10-06 09:15:00+02'),
(11, 'Claim Submission', 'Claims ready for review', 'There are new October demi claims awaiting your review.', FALSE, '2026-10-07 16:35:00+02'),
(15, 'Administration', 'Appointments awaiting review', 'A new demi appointment is ready for administrator review.', FALSE, '2026-10-02 16:25:00+02');

-- 17. Insert Security Session Tokens
INSERT INTO "SECURITY_TOKEN" ("UserID", "JWT_Token", "IssuedAt", "ExpiresAt") VALUES 
(1, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwibmFtZSI6IlNpcGhvIE5kbG92dSJ9', '2026-08-29 08:00:00+02', '2026-08-30 08:00:00+02'),
(2, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwibmFtZSI6IlBpZXRlciBCb3RoYSJ9', '2026-08-29 08:15:00+02', '2026-08-30 08:15:00+02'),
(3, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwibmFtZSI6IkxlcmF0byBNb2tvZW5hIn0', '2026-08-29 09:00:00+02', '2026-08-30 09:00:00+02'),
(11, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMSIsIm5hbWUiOiJBbGFuIFNtaXRoIn0', '2026-08-29 07:30:00+02', '2026-08-30 07:30:00+02'),
(15, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNSIsIm5hbWUiOiJFcmljIEpvaG5zb24ifQ', '2026-08-29 07:00:00+02', '2026-08-30 07:00:00+02');

-- 18. Seed position responsibilities for a representative mix of modules.
INSERT INTO "RESPONSIBILITY" ("PositionID", "Description")
VALUES
    (1, 'Assist with practical session demonstrations and lab setup.'),
    (1, 'Grade weekly assignment submissions and provide feedback.'),
    (1, 'Hold two office hours per week for student consultations.'),
    (8, 'Help students debug Java exercises during CMPG323 practicals.'),
    (8, 'Mark weekly programming exercises and provide constructive feedback.'),
    (9, 'Support SQL laboratory sessions and review database assignments.'),
    (9, 'Run a weekly consultation hour for database design questions.'),
    (10, 'Prepare worked examples and facilitate INGM311 tutorial groups.'),
    (11, 'Assist with renewable energy project consultations and lab preparation.'),
    (12, 'Demonstrate fluid mechanics laboratory procedures and safety.'),
    (13, 'Help students interpret signal processing practical results.'),
    (14, 'Prepare tutorial questions and support INGM311 student consultations.'),
    (15, 'Assist with CMPG221 data structures practicals and marking.');

COMMIT;