-- ============================================================================
-- DEMI APPLICATION AND CLAIMS MANAGEMENT SYSTEM (DACMS)
-- PostgreSQL DDL Script
-- ============================================================================

DROP TABLE IF EXISTS "SECURITY_TOKEN" CASCADE;
DROP TABLE IF EXISTS "NOTIFICATION" CASCADE;
DROP TABLE IF EXISTS "WORK_SESSION" CASCADE;
DROP TABLE IF EXISTS "REMUNERATION_CLAIM" CASCADE;
DROP TABLE IF EXISTS "DEMI_POSITION" CASCADE;
DROP TABLE IF EXISTS "DEMI_APPLICATION" CASCADE;
DROP TABLE IF EXISTS "DEMI_LISTING" CASCADE;
DROP TABLE IF EXISTS "STUDENT_MODULE_GRADE" CASCADE;
DROP TABLE IF EXISTS "MODULE_BUDGET" CASCADE;
DROP TABLE IF EXISTS "LECTURER_MODULE" CASCADE;
DROP TABLE IF EXISTS "NWU_MODULE" CASCADE;
DROP TABLE IF EXISTS "ORGANISATIONAL_ENTITY" CASCADE;
DROP TABLE IF EXISTS "SUPPORTING_DOCUMENT" CASCADE;
DROP TABLE IF EXISTS "ADMINISTRATOR" CASCADE;
DROP TABLE IF EXISTS "LECTURER" CASCADE;
DROP TABLE IF EXISTS "STUDENT" CASCADE;
DROP TABLE IF EXISTS "APP_USER" CASCADE;
DROP TABLE IF EXISTS "PAYMENT_SCALE" CASCADE;
DROP TABLE IF EXISTS "SYSTEM_ROLE" CASCADE;

BEGIN;

CREATE TABLE "SYSTEM_ROLE" (
    "RoleID" INT GENERATED BY DEFAULT AS IDENTITY,
    "RoleName" varchar(20) NOT NULL,
    CONSTRAINT "PK_SYSTEM_ROLE" PRIMARY KEY ("RoleID"),
    CONSTRAINT "UQ_SYSTEM_ROLE_RoleName" UNIQUE ("RoleName")
);

CREATE TABLE "PAYMENT_SCALE" (
    "ScaleID" INT GENERATED BY DEFAULT AS IDENTITY,
    "RoleLevel" varchar(50) NOT NULL,
    "StandardHourlyRate" numeric(10,2) NOT NULL,
    "EffectiveYear" int NOT NULL,
    CONSTRAINT "PK_PAYMENT_SCALE" PRIMARY KEY ("ScaleID")
);

CREATE TABLE "ORGANISATIONAL_ENTITY" (
    "OE_ID" INT GENERATED BY DEFAULT AS IDENTITY,
    "OE_Code" varchar(10) NOT NULL,
    "OEName" varchar(150) NOT NULL,
    "FacultyName" varchar(100) DEFAULT 'Faculty of Natural & Agricultural Sciences',
    CONSTRAINT "PK_ORGANISATIONAL_ENTITY" PRIMARY KEY ("OE_ID"),
    CONSTRAINT "UQ_ORGANISATIONAL_ENTITY_OE_Code" UNIQUE ("OE_Code")
);

CREATE TABLE "NWU_MODULE" (
    "ModuleID" INT GENERATED BY DEFAULT AS IDENTITY,
    "ModuleCode" varchar(20) NOT NULL,
    "ModuleName" varchar(150) NOT NULL,
    "Description" text,
    "MinAcademicRequirement" numeric(5,2) NOT NULL,
    "OE_ID" int NOT NULL,
    CONSTRAINT "PK_NWU_MODULE" PRIMARY KEY ("ModuleID"),
    CONSTRAINT "UQ_NWU_MODULE_ModuleCode" UNIQUE ("ModuleCode"),
    CONSTRAINT "FK_NWU_MODULE_OE" FOREIGN KEY ("OE_ID")
        REFERENCES "ORGANISATIONAL_ENTITY" ("OE_ID")
);

CREATE TABLE "APP_USER" (
    "UserID" INT GENERATED BY DEFAULT AS IDENTITY,
    "Title" varchar(10) NOT NULL DEFAULT 'Mx',
    "FName" varchar(100) NOT NULL,
    "LName" varchar(100) NOT NULL,
    "Email" varchar(100) NOT NULL,
    "PasswordHash" varchar(255) NOT NULL,
    "RoleID" int NOT NULL,
    "CreatedAt" timestamptz DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_APP_USER" PRIMARY KEY ("UserID"),
    CONSTRAINT "UQ_APP_USER_Email" UNIQUE ("Email"),
    CONSTRAINT "FK_APP_USER_SYSTEM_ROLE"
        FOREIGN KEY ("RoleID")
        REFERENCES "SYSTEM_ROLE" ("RoleID")
        DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE "STUDENT" (
    "StudentID" int,
    "StudentNumber" varchar(20) NOT NULL,
    "StudyLevel" varchar(50) NOT NULL,
    "ContactDetails" varchar(255),
    "BankName" varchar(100),
    "AccountNumber" varchar(50),
    "BranchCode" varchar(20),
    "ID_PassportNumber" varchar(50),
    "Title" varchar(20),
    "Gender" varchar(30),
    "DateOfBirth" date,
    "IncomeTaxNumber" varchar(50),
    "SACitizen" boolean,
    "ResidentialAddress" text,
    "PostalAddress" text,
    "NextOfKinName" varchar(150),
    "NextOfKinMobile" varchar(50),
    "HighestQualification" varchar(150),
    "AccountType" varchar(50),
    "AccountHolderName" varchar(150),
    CONSTRAINT "PK_STUDENT" PRIMARY KEY ("StudentID"),
    CONSTRAINT "UQ_STUDENT_StudentNumber" UNIQUE ("StudentNumber"),
    CONSTRAINT "FK_STUDENT_User" FOREIGN KEY ("StudentID")
        REFERENCES "APP_USER" ("UserID")
);

CREATE TABLE "SUPPORTING_DOCUMENT" (
    "DocumentID" INT GENERATED BY DEFAULT AS IDENTITY,
    "StudentID" int NOT NULL,
    "DocumentType" varchar(100) NOT NULL,
    "FilePath" varchar(500) NOT NULL,
    "UploadTimestamp" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_SUPPORTING_DOCUMENT" PRIMARY KEY ("DocumentID"),
    CONSTRAINT "FK_SUPPORTING_DOCUMENT_Student" FOREIGN KEY ("StudentID")
        REFERENCES "STUDENT" ("StudentID")
);

CREATE TABLE "LECTURER" (
    "LecturerID" int,
    "Department" varchar(150),
    "OE_ID" int,
    CONSTRAINT "PK_LECTURER" PRIMARY KEY ("LecturerID"),
    CONSTRAINT "FK_LECTURER_User" FOREIGN KEY ("LecturerID")
        REFERENCES "APP_USER" ("UserID"),
    CONSTRAINT "FK_LECTURER_OE" FOREIGN KEY ("OE_ID")
        REFERENCES "ORGANISATIONAL_ENTITY" ("OE_ID")
);

CREATE TABLE "LECTURER_MODULE" (
    "LecturerID" int NOT NULL,
    "ModuleID" int NOT NULL,
    CONSTRAINT "PK_LECTURER_MODULE" PRIMARY KEY ("LecturerID", "ModuleID"),
    CONSTRAINT "FK_LECTURER_MODULE_Lecturer" FOREIGN KEY ("LecturerID")
        REFERENCES "LECTURER" ("LecturerID"),
    CONSTRAINT "FK_LECTURER_MODULE_Module" FOREIGN KEY ("ModuleID")
        REFERENCES "NWU_MODULE" ("ModuleID")
);

CREATE TABLE "ADMINISTRATOR" (
    "AdminID" int,
    "MFA_Enabled" boolean NOT NULL DEFAULT false,
    "BudgetAllocationRights" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_ADMINISTRATOR" PRIMARY KEY ("AdminID"),
    CONSTRAINT "FK_ADMINISTRATOR_User" FOREIGN KEY ("AdminID")
        REFERENCES "APP_USER" ("UserID")
);

CREATE TABLE "SECURITY_TOKEN" (
    "TokenID" INT GENERATED BY DEFAULT AS IDENTITY,
    "UserID" int NOT NULL,
    "JWT_Token" text NOT NULL,
    "IssuedAt" timestamptz NOT NULL,
    "ExpiresAt" timestamptz NOT NULL,
    CONSTRAINT "PK_SECURITY_TOKEN" PRIMARY KEY ("TokenID"),
    CONSTRAINT "FK_SECURITY_TOKEN_User" FOREIGN KEY ("UserID")
        REFERENCES "APP_USER" ("UserID")
);

CREATE TABLE "MODULE_BUDGET" (
    "BudgetID" INT GENERATED BY DEFAULT AS IDENTITY,
    "ModuleID" int NOT NULL,
    "LecturerID" int NOT NULL,
    "AllocatedBudget" numeric(12,2) NOT NULL,
    "CurrentBudgetUsage" numeric(12,2) NOT NULL DEFAULT 0,
    "MaxAllowableWorkHours" numeric(10,2) NOT NULL,
    "AcademicYear" int NOT NULL,
    CONSTRAINT "PK_MODULE_BUDGET" PRIMARY KEY ("BudgetID"),
    CONSTRAINT "FK_MODULE_BUDGET_Module" FOREIGN KEY ("ModuleID")
        REFERENCES "NWU_MODULE" ("ModuleID"),
    CONSTRAINT "FK_MODULE_BUDGET_Lecturer" FOREIGN KEY ("LecturerID")
        REFERENCES "LECTURER" ("LecturerID")
);

CREATE TABLE "STUDENT_MODULE_GRADE" (
    "GradeID" INT GENERATED BY DEFAULT AS IDENTITY,
    "StudentID" int NOT NULL,
    "ModuleID" int NOT NULL,
    "GradeAchieved" numeric(5,2) NOT NULL,
    CONSTRAINT "PK_STUDENT_MODULE_GRADE" PRIMARY KEY ("GradeID"),
    CONSTRAINT "FK_STUDENT_MODULE_GRADE_Student" FOREIGN KEY ("StudentID")
        REFERENCES "STUDENT" ("StudentID"),
    CONSTRAINT "FK_STUDENT_MODULE_GRADE_Module" FOREIGN KEY ("ModuleID")
        REFERENCES "NWU_MODULE" ("ModuleID")
);

CREATE TABLE "DEMI_LISTING" (
    "ListingID" INT GENERATED BY DEFAULT AS IDENTITY,
    "ModuleID" int NOT NULL,
    "LecturerID" int NOT NULL,
    "Deadline" timestamptz NOT NULL,
    "MinimumGrade" numeric(5,2) NOT NULL,
    CONSTRAINT "PK_DEMI_LISTING" PRIMARY KEY ("ListingID"),
    CONSTRAINT "FK_DEMI_LISTING_Module" FOREIGN KEY ("ModuleID")
        REFERENCES "NWU_MODULE" ("ModuleID"),
    CONSTRAINT "FK_DEMI_LISTING_Lecturer" FOREIGN KEY ("LecturerID")
        REFERENCES "LECTURER" ("LecturerID")
);

CREATE TABLE "DEMI_APPLICATION" (
    "ApplicationID" INT GENERATED BY DEFAULT AS IDENTITY,
    "StudentID" INT NOT NULL,
    "ListingID" INT NOT NULL,
    "ApplicationStatus" VARCHAR(30) DEFAULT 'Pending',
    "VerificationEligibilityStatus" VARCHAR(30),
    "DateSubmitted" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_DEMI_APPLICATION" PRIMARY KEY ("ApplicationID"),
    CONSTRAINT "CHK_DEMI_APPLICATION_Status" CHECK (
        "ApplicationStatus" IN ('Pending', 'In Review', 'Approved', 'Rejected', 'Returned')
    )
);

CREATE TABLE "DEMI_POSITION" (
    "PositionID" INT GENERATED BY DEFAULT AS IDENTITY,
    "ApplicationID" INT NOT NULL,
    "PaymentScaleID" INT NOT NULL,
    "TempBudgetPositionNo" VARCHAR(30),
    "AccountingCombination" VARCHAR(30),
    "TotalAllocatedHours" NUMERIC(5, 2) DEFAULT 0.00,
    "PositionStatus" VARCHAR(30) DEFAULT 'Pending Admin Review',
    "StartDate" TIMESTAMPTZ,
    "TerminationDate" TIMESTAMPTZ,
    "AdminComment" TEXT,
    CONSTRAINT "PK_DEMI_POSITION" PRIMARY KEY ("PositionID"),
    CONSTRAINT "FK_DEMI_POSITION_DEMI_APPLICATION" FOREIGN KEY ("ApplicationID")
        REFERENCES "DEMI_APPLICATION" ("ApplicationID") ON DELETE CASCADE,
    CONSTRAINT "CHK_DEMI_POSITION_Status" CHECK (
        "PositionStatus" IN ('Pending Admin Review', 'Approved', 'Rejected', 'Returned')
    )
);

CREATE TABLE "RESPONSIBILITY" (
    "ResponsibilityID" INT GENERATED BY DEFAULT AS IDENTITY,
    "PositionID" INT NOT NULL,
    "Description" TEXT NOT NULL,
    CONSTRAINT "PK_RESPONSIBILITY" PRIMARY KEY ("ResponsibilityID"),
    CONSTRAINT "FK_RESPONSIBILITY_DEMI_POSITION" FOREIGN KEY ("PositionID")
        REFERENCES "DEMI_POSITION" ("PositionID") ON DELETE CASCADE
);

CREATE TABLE "WORK_SESSION" (
    "SessionID" INT GENERATED BY DEFAULT AS IDENTITY,
    "PositionID" int NOT NULL,
    "ActivityDescription" varchar(200),
    "StartTime" timestamptz NOT NULL,
    "EndTime" timestamptz,
    "TotalHoursWorked" decimal(5,2),
    "EstimatedRemuneration" decimal(8,2),
    "LecturerApproval" boolean DEFAULT false,
    CONSTRAINT "PK_WORK_SESSION" PRIMARY KEY ("SessionID"),
    CONSTRAINT "FK_WORK_SESSION_DEMI_POSITION" FOREIGN KEY ("PositionID")
        REFERENCES "DEMI_POSITION" ("PositionID") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE "REMUNERATION_CLAIM" (
    "ClaimID" INT GENERATED BY DEFAULT AS IDENTITY,
    "ClaimReferenceNumber" varchar(50) NOT NULL,
    "ApplicationID" int NOT NULL,
    "ModuleID" int NOT NULL,
    "PeriodStartDate" date,
    "PeriodEndDate" date,
    "TotalHoursClaimed" decimal(5,2) NOT NULL,
    "TotalClaimAmount" decimal(10,2) NOT NULL,
    "HourlyRateApplied" decimal(10,2) NOT NULL,
    "ClaimStatus" varchar(20) DEFAULT 'Pending',
    "SubmissionDate" timestamptz DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_REMUNERATION_CLAIM" PRIMARY KEY ("ClaimID"),
    CONSTRAINT "UQ_REMUNERATION_CLAIM_ReferenceNumber" UNIQUE ("ClaimReferenceNumber"),
    CONSTRAINT "FK_REMUNERATION_CLAIM_DEMI_APPLICATION" FOREIGN KEY ("ApplicationID")
        REFERENCES "DEMI_APPLICATION" ("ApplicationID") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT "FK_REMUNERATION_CLAIM_NWU_MODULE" FOREIGN KEY ("ModuleID")
        REFERENCES "NWU_MODULE" ("ModuleID") DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE "NOTIFICATION" (
  "NotificationID" INT GENERATED BY DEFAULT AS IDENTITY,
  "RecipientUserID" int NOT NULL,
  "NotificationTitle" varchar(50) NOT NULL,
  "NotificationType" varchar(50) NOT NULL,
  "Subject" varchar(100),
  "Message" text NOT NULL,
  "IsRead" boolean DEFAULT false,
  "CreatedTimestamp" timestamptz DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY ("NotificationID"),
  CONSTRAINT "FK_NOTIFICATION_APP_USER"
    FOREIGN KEY ("RecipientUserID")
    REFERENCES "APP_USER" ("UserID")
    DEFERRABLE INITIALLY IMMEDIATE
);