--DACMS NEW INIT SQL 
--NEW SEED DATA

DROP TABLE IF EXISTS "NOTIFICATION" CASCADE;
DROP TABLE IF EXISTS "REMUNERATION_CLAIM" CASCADE;
DROP TABLE IF EXISTS "WORK_SESSION" CASCADE;
DROP TABLE IF EXISTS "DEMI_POSITION" CASCADE;
DROP TABLE IF EXISTS "DEMI_APPLICATION" CASCADE;
DROP TABLE IF EXISTS "DEMI_LISTING" CASCADE;
DROP TABLE IF EXISTS "STUDENT_MODULE_GRADE" CASCADE;
DROP TABLE IF EXISTS "MODULE_BUDGET" CASCADE;
DROP TABLE IF EXISTS "SECURITY_TOKEN" CASCADE;
DROP TABLE IF EXISTS "ADMINISTRATOR" CASCADE;
DROP TABLE IF EXISTS "LECTURER_MODULE" CASCADE;
DROP TABLE IF EXISTS "LECTURER" CASCADE;
DROP TABLE IF EXISTS "SUPPORTING_DOCUMENT" CASCADE;
DROP TABLE IF EXISTS "STUDENT" CASCADE;
DROP TABLE IF EXISTS "APP_USER" CASCADE;
DROP TABLE IF EXISTS "NWU_MODULE" CASCADE;
DROP TABLE IF EXISTS "PAYMENT_SCALE" CASCADE;
DROP TABLE IF EXISTS "SYSTEM_ROLE" CASCADE;
DROP TABLE IF EXISTS "ORGANISATIONAL_ENTITY" CASCADE;

BEGIN;

CREATE TABLE "SYSTEM_ROLE" (
    "RoleID" INT GENERATED BY DEFAULT AS IDENTITY,
    "RoleName" varchar(50) NOT NULL,
    CONSTRAINT "PK_SYSTEM_ROLE" PRIMARY KEY ("RoleID"),
    CONSTRAINT "UQ_SYSTEM_ROLE_RoleName" UNIQUE ("RoleName")
);

CREATE TABLE "PAYMENT_SCALE" (
    "ScaleID" INT GENERATED BY DEFAULT AS IDENTITY,
    "RoleLevel" varchar(50) NOT NULL,
    "StandardHourlyRate" numeric(10,2) NOT NULL,
    "EffectiveYear" int NOT NULL,
    CONSTRAINT "PK_PAYMENT_SCALE" PRIMARY KEY ("ScaleID")
);

CREATE TABLE "ORGANISATIONAL_ENTITY" (
    "OE_ID" INT GENERATED BY DEFAULT AS IDENTITY,
    "OE_Code" varchar(10) NOT NULL,
    "OEName" varchar(150) NOT NULL,
    "FacultyName" varchar(100) DEFAULT 'Faculty of Natural & Agricultural Sciences',
    CONSTRAINT "PK_ORGANISATIONAL_ENTITY" PRIMARY KEY ("OE_ID"),
    CONSTRAINT "UQ_ORGANISATIONAL_ENTITY_OE_Code" UNIQUE ("OE_Code")
);

CREATE TABLE "NWU_MODULE" (
    "ModuleID" INT GENERATED BY DEFAULT AS IDENTITY,
    "ModuleCode" varchar(20) NOT NULL,
    "ModuleName" varchar(150) NOT NULL,
    "Description" text,
    "MinAcademicRequirement" numeric(5,2) NOT NULL,
    "OE_ID" int NOT NULL,
    CONSTRAINT "PK_NWU_MODULE" PRIMARY KEY ("ModuleID"),
    CONSTRAINT "UQ_NWU_MODULE_ModuleCode" UNIQUE ("ModuleCode"),
    CONSTRAINT "FK_NWU_MODULE_OE" FOREIGN KEY ("OE_ID")
        REFERENCES "ORGANISATIONAL_ENTITY" ("OE_ID")
);

CREATE TABLE "APP_USER" (
    "UserID" INT GENERATED BY DEFAULT AS IDENTITY,
    "FName" varchar(100) NOT NULL,
    "LName" varchar(100) NOT NULL,
    "Email" varchar(255) NOT NULL,
    "PasswordHash" varchar(255) NOT NULL,
    "RoleID" int NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_APP_USER" PRIMARY KEY ("UserID"),
    CONSTRAINT "UQ_APP_USER_Email" UNIQUE ("Email"),
    CONSTRAINT "FK_APP_USER_Role" FOREIGN KEY ("RoleID")
        REFERENCES "SYSTEM_ROLE" ("RoleID")
);

CREATE TABLE "STUDENT" (
    "StudentID" int,
    "StudentNumber" varchar(20) NOT NULL,
    "StudyLevel" varchar(50) NOT NULL,
    "ContactDetails" varchar(255),
    "BankName" varchar(100),
    "AccountNumber" varchar(50),
    "BranchCode" varchar(20),
    "ID_PassportNumber" varchar(50),
    "Title" varchar(20),
    "Gender" varchar(30),
    "DateOfBirth" date,
    "IncomeTaxNumber" varchar(50),
    "SACitizen" boolean,
    "ResidentialAddress" text,
    "PostalAddress" text,
    "NextOfKinName" varchar(150),
    "NextOfKinMobile" varchar(50),
    "HighestQualification" varchar(150),
    "AccountType" varchar(50),
    "AccountHolderName" varchar(150),
    CONSTRAINT "PK_STUDENT" PRIMARY KEY ("StudentID"),
    CONSTRAINT "UQ_STUDENT_StudentNumber" UNIQUE ("StudentNumber"),
    CONSTRAINT "FK_STUDENT_User" FOREIGN KEY ("StudentID")
        REFERENCES "APP_USER" ("UserID")
);

CREATE TABLE "SUPPORTING_DOCUMENT" (
    "DocumentID" INT GENERATED BY DEFAULT AS IDENTITY,
    "StudentID" int NOT NULL,
    "DocumentType" varchar(100) NOT NULL,
    "FilePath" varchar(500) NOT NULL,
    "UploadTimestamp" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_SUPPORTING_DOCUMENT" PRIMARY KEY ("DocumentID"),
    CONSTRAINT "FK_SUPPORTING_DOCUMENT_Student" FOREIGN KEY ("StudentID")
        REFERENCES "STUDENT" ("StudentID")
);

CREATE TABLE "LECTURER" (
    "LecturerID" int,
    "Department" varchar(150),
    "OE_ID" int,
    CONSTRAINT "PK_LECTURER" PRIMARY KEY ("LecturerID"),
    CONSTRAINT "FK_LECTURER_User" FOREIGN KEY ("LecturerID")
        REFERENCES "APP_USER" ("UserID"),
    CONSTRAINT "FK_LECTURER_OE" FOREIGN KEY ("OE_ID")
        REFERENCES "ORGANISATIONAL_ENTITY" ("OE_ID")
);

CREATE TABLE "LECTURER_MODULE" (
    "LecturerID" int NOT NULL,
    "ModuleID" int NOT NULL,
    CONSTRAINT "PK_LECTURER_MODULE" PRIMARY KEY ("LecturerID", "ModuleID"),
    CONSTRAINT "FK_LECTURER_MODULE_Lecturer" FOREIGN KEY ("LecturerID")
        REFERENCES "LECTURER" ("LecturerID"),
    CONSTRAINT "FK_LECTURER_MODULE_Module" FOREIGN KEY ("ModuleID")
        REFERENCES "NWU_MODULE" ("ModuleID")
);

CREATE TABLE "ADMINISTRATOR" (
    "AdminID" int,
    "MFA_Enabled" boolean NOT NULL DEFAULT false,
    "BudgetAllocationRights" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_ADMINISTRATOR" PRIMARY KEY ("AdminID"),
    CONSTRAINT "FK_ADMINISTRATOR_User" FOREIGN KEY ("AdminID")
        REFERENCES "APP_USER" ("UserID")
);

CREATE TABLE "SECURITY_TOKEN" (
    "TokenID" INT GENERATED BY DEFAULT AS IDENTITY,
    "UserID" int NOT NULL,
    "JWT_Token" text NOT NULL,
    "IssuedAt" timestamptz NOT NULL,
    "ExpiresAt" timestamptz NOT NULL,
    CONSTRAINT "PK_SECURITY_TOKEN" PRIMARY KEY ("TokenID"),
    CONSTRAINT "FK_SECURITY_TOKEN_User" FOREIGN KEY ("UserID")
        REFERENCES "APP_USER" ("UserID")
);

CREATE TABLE "MODULE_BUDGET" (
    "BudgetID" INT GENERATED BY DEFAULT AS IDENTITY,
    "ModuleID" int NOT NULL,
    "LecturerID" int NOT NULL,
    "AllocatedBudget" numeric(12,2) NOT NULL,
    "CurrentBudgetUsage" numeric(12,2) NOT NULL DEFAULT 0,
    "MaxAllowableWorkHours" numeric(10,2) NOT NULL,
    "AcademicYear" int NOT NULL,
    CONSTRAINT "PK_MODULE_BUDGET" PRIMARY KEY ("BudgetID"),
    CONSTRAINT "FK_MODULE_BUDGET_Module" FOREIGN KEY ("ModuleID")
        REFERENCES "NWU_MODULE" ("ModuleID"),
    CONSTRAINT "FK_MODULE_BUDGET_Lecturer" FOREIGN KEY ("LecturerID")
        REFERENCES "LECTURER" ("LecturerID")
);

CREATE TABLE "STUDENT_MODULE_GRADE" (
    "GradeID" INT GENERATED BY DEFAULT AS IDENTITY,
    "StudentID" int NOT NULL,
    "ModuleID" int NOT NULL,
    "GradeAchieved" numeric(5,2) NOT NULL,
    CONSTRAINT "PK_STUDENT_MODULE_GRADE" PRIMARY KEY ("GradeID"),
    CONSTRAINT "FK_STUDENT_MODULE_GRADE_Student" FOREIGN KEY ("StudentID")
        REFERENCES "STUDENT" ("StudentID"),
    CONSTRAINT "FK_STUDENT_MODULE_GRADE_Module" FOREIGN KEY ("ModuleID")
        REFERENCES "NWU_MODULE" ("ModuleID")
);

CREATE TABLE "DEMI_LISTING" (
    "ListingID" INT GENERATED BY DEFAULT AS IDENTITY,
    "ModuleID" int NOT NULL,
    "LecturerID" int NOT NULL,
    "Deadline" timestamptz NOT NULL,
    "MinimumGrade" numeric(5,2) NOT NULL,
    CONSTRAINT "PK_DEMI_LISTING" PRIMARY KEY ("ListingID"),
    CONSTRAINT "FK_DEMI_LISTING_Module" FOREIGN KEY ("ModuleID")
        REFERENCES "NWU_MODULE" ("ModuleID"),
    CONSTRAINT "FK_DEMI_LISTING_Lecturer" FOREIGN KEY ("LecturerID")
        REFERENCES "LECTURER" ("LecturerID")
);

CREATE TABLE "DEMI_APPLICATION" (
    "ApplicationID" INT GENERATED BY DEFAULT AS IDENTITY,
    "StudentID" int NOT NULL,
    "ListingID" int NOT NULL,
    "ApplicationStatus" varchar(50) NOT NULL,
    "VerificationEligibilityStatus" varchar(50) NOT NULL,
    "DateSubmitted" timestamptz NOT NULL,
    CONSTRAINT "PK_DEMI_APPLICATION" PRIMARY KEY ("ApplicationID"),
    CONSTRAINT "FK_DEMI_APPLICATION_Student" FOREIGN KEY ("StudentID")
        REFERENCES "STUDENT" ("StudentID"),
    CONSTRAINT "FK_DEMI_APPLICATION_Listing" FOREIGN KEY ("ListingID")
        REFERENCES "DEMI_LISTING" ("ListingID")
);

CREATE TABLE "DEMI_POSITION" (
    "PositionID" INT GENERATED BY DEFAULT AS IDENTITY,
    "ApplicationID" int NOT NULL,
    "PaymentScaleID" int NOT NULL,
    "TempBudgetPositionNo" varchar(100),
    "AccountingCombination" varchar(100),
    "TotalAllocatedHours" numeric(10,2),
    "StartDate" date NOT NULL,
    "TerminationDate" date,
    CONSTRAINT "PK_DEMI_POSITION" PRIMARY KEY ("PositionID"),
    CONSTRAINT "UQ_DEMI_POSITION_ApplicationID" UNIQUE ("ApplicationID"),
    CONSTRAINT "FK_DEMI_POSITION_Application" FOREIGN KEY ("ApplicationID")
        REFERENCES "DEMI_APPLICATION" ("ApplicationID"),
    CONSTRAINT "FK_DEMI_POSITION_PaymentScale" FOREIGN KEY ("PaymentScaleID")
        REFERENCES "PAYMENT_SCALE" ("ScaleID")
);

CREATE TABLE "WORK_SESSION" (
    "SessionID" INT GENERATED BY DEFAULT AS IDENTITY,
    "PositionID" int NOT NULL,
    "StartTime" timestamptz NOT NULL,
    "EndTime" timestamptz NOT NULL,
    "TotalHoursWorked" numeric(10,2) NOT NULL,
    "EstimatedRemuneration" numeric(12,2) NOT NULL,
    "LecturerApproval" boolean NOT NULL DEFAULT false,
    "ActivityDescription" varchar(255),
    CONSTRAINT "PK_WORK_SESSION" PRIMARY KEY ("SessionID"),
    CONSTRAINT "FK_WORK_SESSION_Position" FOREIGN KEY ("PositionID")
        REFERENCES "DEMI_POSITION" ("PositionID")
);

CREATE TABLE "REMUNERATION_CLAIM" (
    "ClaimID" INT GENERATED BY DEFAULT AS IDENTITY,
    "ClaimReferenceNumber" varchar(100) NOT NULL,
    "ApplicationID" int NOT NULL,
    "ModuleID" int NOT NULL,
    "PeriodStartDate" date,
    "PeriodEndDate" date,
    "TotalHoursClaimed" numeric(10,2) NOT NULL,
    "TotalClaimAmount" numeric(12,2) NOT NULL,
    "HourlyRateApplied" numeric(10,2) NOT NULL,
    "ClaimStatus" varchar(50) NOT NULL,
    "SubmissionDate" timestamptz NOT NULL,
    CONSTRAINT "PK_REMUNERATION_CLAIM" PRIMARY KEY ("ClaimID"),
    CONSTRAINT "UQ_REMUNERATION_CLAIM_Reference" UNIQUE ("ClaimReferenceNumber"),
    CONSTRAINT "FK_REMUNERATION_CLAIM_Application" FOREIGN KEY ("ApplicationID")
        REFERENCES "DEMI_APPLICATION" ("ApplicationID"),
    CONSTRAINT "FK_REMUNERATION_CLAIM_Module" FOREIGN KEY ("ModuleID")
        REFERENCES "NWU_MODULE" ("ModuleID")
);

CREATE TABLE "NOTIFICATION" (
    "NotificationID" INT GENERATED BY DEFAULT AS IDENTITY,
    "RecipientUserID" int NOT NULL,
    "NotificationType" varchar(100) NOT NULL,
    "Subject" varchar(255),
    "Message" text NOT NULL,
    "IsRead" boolean NOT NULL DEFAULT false,
    "CreatedTimestamp" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY ("NotificationID"),
    CONSTRAINT "FK_NOTIFICATION_User" FOREIGN KEY ("RecipientUserID")
        REFERENCES "APP_USER" ("UserID")
);

-- Seed data

INSERT INTO "SYSTEM_ROLE" ("RoleID", "RoleName") VALUES
(1, 'Student'),
(2, 'Lecturer'),
(3, 'Administrator');

INSERT INTO "PAYMENT_SCALE" ("ScaleID", "RoleLevel", "StandardHourlyRate", "EffectiveYear") VALUES
(1, 'Level 1', 86.75, 2026),
(2, 'Level 2', 107.80, 2026);

INSERT INTO "ORGANISATIONAL_ENTITY" ("OE_ID", "OE_Code", "OEName", "FacultyName") VALUES
(1, '8412', 'School of Computer Science and Information Systems', 'Faculty of Natural & Agricultural Sciences'),
(2, '8413', 'School of Electrical, Electronic and Computer Engineering', 'Faculty of Engineering'),
(3, '8414', 'School of Mechanical Engineering', 'Faculty of Engineering'),
(4, '8415', 'School of Chemical Engineering', 'Faculty of Engineering');

INSERT INTO "NWU_MODULE" ("ModuleID", "ModuleCode", "ModuleName", "Description", "MinAcademicRequirement", "OE_ID") VALUES
(1, 'CMPG323', 'IT Development', 'Information Technology Development', 65.00, 1),
(2, 'CMPG311', 'Software Engineering', 'Software Engineering', 65.00, 1),
(3, 'CMPG221', 'Computer Networks', 'Computer Networks', 60.00, 1),
(4, 'EERI124', 'Electrical Engineering', 'Electrical Engineering', 60.00, 2),
(5, 'EERI223', 'Electronic Engineering', 'Electronic Engineering', 60.00, 2),
(6, 'INGM311', 'Mechanical Engineering', 'Mechanical Engineering', 65.00, 3),
(7, 'INGM121', 'Engineering Mathematics', 'Engineering Mathematics', 60.00, 3),
(8, 'INGM222', 'Engineering Mechanics', 'Engineering Mechanics', 60.00, 3),
(9, 'INGM412', 'Advanced Mechanical Engineering', 'Advanced Mechanical Engineering', 65.00, 3),
(10, 'REES211', 'Chemical Engineering', 'Chemical Engineering', 60.00, 4);

INSERT INTO "APP_USER" ("UserID", "FName", "LName", "Email", "PasswordHash", "RoleID") VALUES
(1, 'Thato', 'Mooketsi', 'thato.student@nwu.ac.za', 'hashed_password_1', 1),
(2, 'Karabo', 'Molefe', 'karabo.student@nwu.ac.za', 'hashed_password_2', 1),
(3, 'Lerato', 'Mokoena', 'lerato.student@nwu.ac.za', 'hashed_password_3', 1),
(4, 'Tshepo', 'Molefe', 'tshepo.student@nwu.ac.za', 'hashed_password_4', 1),
(5, 'Boitumelo', 'Mokoena', 'boitumelo.student@nwu.ac.za', 'hashed_password_5', 1),
(6, 'Kagiso', 'Molefe', 'kagiso.student@nwu.ac.za', 'hashed_password_6', 1),
(7, 'Mpho', 'Mokoena', 'mpho.student@nwu.ac.za', 'hashed_password_7', 1),
(8, 'Refilwe', 'Molefe', 'refilwe.student@nwu.ac.za', 'hashed_password_8', 1),
(9, 'Neo', 'Mokoena', 'neo.student@nwu.ac.za', 'hashed_password_9', 1),
(10, 'Olebogeng', 'Molefe', 'olebogeng.student@nwu.ac.za', 'hashed_password_10', 1),
(11, 'Alan', 'Smith', 'alan.lecturer@nwu.ac.za', 'hashed_password_11', 2),
(12, 'Beatrice', 'Jones', 'beatrice.lecturer@nwu.ac.za', 'hashed_password_12', 2),
(13, 'Charles', 'Brown', 'charles.lecturer@nwu.ac.za', 'hashed_password_13', 2),
(14, 'Diane', 'Williams', 'diane.lecturer@nwu.ac.za', 'hashed_password_14', 2),
(15, 'Admin', 'One', 'admin.one@nwu.ac.za', 'hashed_password_15', 3),
(16, 'Admin', 'Two', 'admin.two@nwu.ac.za', 'hashed_password_16', 3);

INSERT INTO "STUDENT" (
    "StudentID", "StudentNumber", "StudyLevel", "ContactDetails",
    "BankName", "AccountNumber", "BranchCode", "ID_PassportNumber",
    "Title", "Gender", "DateOfBirth", "IncomeTaxNumber", "SACitizen",
    "ResidentialAddress", "PostalAddress", "NextOfKinName", "NextOfKinMobile",
    "HighestQualification", "AccountType", "AccountHolderName"
) VALUES
(1, '40000001', 'Final Year', '0710000001', 'FNB', '62000000001', '250655', 'ID000000001', 'Mr', 'Male', '2004-04-15', 'ITN000000001', true, 'Potchefstroom', 'Potchefstroom', 'Family Contact 1', '0711000001', 'Matric', 'Savings', 'Thato Mooketsi'),
(2, '40000002', 'Final Year', '0710000002', 'FNB', '62000000002', '250655', 'ID000000002', 'Ms', 'Female', '2004-05-20', 'ITN000000002', true, 'Potchefstroom', 'Potchefstroom', 'Family Contact 2', '0711000002', 'Matric', 'Savings', 'Karabo Molefe'),
(3, '40000003', 'Third Year', '0710000003', 'ABSA', '62000000003', '632005', 'ID000000003', 'Ms', 'Female', '2005-01-10', 'ITN000000003', true, 'Potchefstroom', 'Potchefstroom', 'Family Contact 3', '0711000003', 'Matric', 'Savings', 'Lerato Mokoena'),
(4, '40000004', 'Third Year', '0710000004', 'Nedbank', '62000000004', '198765', 'ID000000004', 'Mr', 'Male', '2005-02-14', 'ITN000000004', true, 'Potchefstroom', 'Potchefstroom', 'Family Contact 4', '0711000004', 'Matric', 'Savings', 'Tshepo Molefe'),
(5, '40000005', 'Third Year', '0710000005', 'Standard Bank', '62000000005', '051001', 'ID000000005', 'Ms', 'Female', '2005-03-18', 'ITN000000005', true, 'Potchefstroom', 'Potchefstroom', 'Family Contact 5', '0711000005', 'Matric', 'Savings', 'Boitumelo Mokoena'),
(6, '40000006', 'Second Year', '0710000006', 'FNB', '62000000006', '250655', 'ID000000006', 'Mr', 'Male', '2006-06-22', 'ITN000000006', true, 'Potchefstroom', 'Potchefstroom', 'Family Contact 6', '0711000006', 'Matric', 'Savings', 'Kagiso Molefe'),
(7, '40000007', 'Second Year', '0710000007', 'ABSA', '62000000007', '632005', 'ID000000007', 'Mr', 'Male', '2006-07-12', 'ITN000000007', true, 'Potchefstroom', 'Potchefstroom', 'Family Contact 7', '0711000007', 'Matric', 'Savings', 'Mpho Mokoena'),
(8, '40000008', 'Second Year', '0710000008', 'Nedbank', '62000000008', '198765', 'ID000000008', 'Ms', 'Female', '2006-08-09', 'ITN000000008', true, 'Potchefstroom', 'Potchefstroom', 'Family Contact 8', '0711000008', 'Matric', 'Savings', 'Refilwe Molefe'),
(9, '40000009', 'First Year', '0710000009', 'Standard Bank', '62000000009', '051001', 'ID000000009', 'Mr', 'Male', '2007-09-01', 'ITN000000009', true, 'Potchefstroom', 'Potchefstroom', 'Family Contact 9', '0711000009', 'Matric', 'Savings', 'Neo Mokoena'),
(10, '40000010', 'First Year', '0710000010', 'FNB', '62000000010', '250655', 'ID000000010', 'Mr', 'Male', '2007-10-05', 'ITN000000010', true, 'Potchefstroom', 'Potchefstroom', 'Family Contact 10', '0711000010', 'Matric', 'Savings', 'Olebogeng Molefe');

INSERT INTO "LECTURER" ("LecturerID", "Department", "OE_ID") VALUES
(11, 'Computer Science and Information Systems', 1),
(12, 'Electrical, Electronic and Computer Engineering', 2),
(13, 'Mechanical Engineering', 3),
(14, 'Chemical Engineering', 4);

INSERT INTO "ADMINISTRATOR" ("AdminID", "MFA_Enabled", "BudgetAllocationRights") VALUES
(15, true, true),
(16, true, true);

INSERT INTO "SUPPORTING_DOCUMENT" ("DocumentID", "StudentID", "DocumentType", "FilePath") VALUES
(1, 1, 'ID Document', '/uploads/student1_id.pdf'),
(2, 1, 'Academic Record', '/uploads/student1_academic.pdf'),
(3, 2, 'ID Document', '/uploads/student2_id.pdf'),
(4, 3, 'ID Document', '/uploads/student3_id.pdf');

INSERT INTO "LECTURER_MODULE" ("LecturerID", "ModuleID") VALUES
(11, 1), (11, 2), (11, 3),
(12, 4), (12, 5),
(13, 6), (13, 7), (13, 8),
(14, 9), (14, 10);

INSERT INTO "MODULE_BUDGET" (
    "BudgetID", "ModuleID", "LecturerID", "AllocatedBudget",
    "CurrentBudgetUsage", "MaxAllowableWorkHours", "AcademicYear"
) VALUES
(1, 1, 11, 17292.96, 824.13, 160.00, 2026),
(2, 2, 11, 15000.00, 607.25, 160.00, 2026),
(3, 3, 11, 12000.00, 0.00, 140.00, 2026),
(4, 4, 12, 14000.00, 1078.00, 160.00, 2026),
(5, 5, 12, 12000.00, 0.00, 140.00, 2026),
(6, 6, 13, 15000.00, 1078.00, 160.00, 2026),
(7, 7, 13, 12000.00, 0.00, 140.00, 2026),
(8, 8, 13, 13000.00, 0.00, 140.00, 2026),
(9, 9, 14, 15000.00, 431.20, 160.00, 2026),
(10, 10, 14, 12000.00, 646.80, 140.00, 2026);

INSERT INTO "STUDENT_MODULE_GRADE" ("GradeID", "StudentID", "ModuleID", "GradeAchieved") VALUES
(1, 1, 1, 78.00),
(2, 1, 2, 75.00),
(3, 2, 1, 72.00),
(4, 2, 2, 68.00),
(5, 3, 3, 65.00),
(6, 4, 4, 70.00),
(7, 5, 5, 75.00),
(8, 6, 6, 72.00),
(9, 7, 7, 66.00),
(10, 8, 8, 71.00),
(11, 9, 9, 69.00),
(12, 10, 10, 73.00);

INSERT INTO "DEMI_LISTING" ("ListingID", "ModuleID", "LecturerID", "Deadline", "MinimumGrade") VALUES
(1, 1, 11, '2026-08-31 23:59:59+02', 65.00),
(2, 2, 11, '2026-08-31 23:59:59+02', 65.00),
(3, 6, 13, '2026-08-31 23:59:59+02', 65.00),
(4, 10, 14, '2026-08-31 23:59:59+02', 60.00),
(5, 10, 14, '2026-09-15 23:59:59+02', 60.00),
(6, 3, 11, '2026-09-15 23:59:59+02', 60.00),
(7, 7, 13, '2026-09-15 23:59:59+02', 60.00),
(8, 8, 13, '2026-09-15 23:59:59+02', 60.00),
(9, 9, 14, '2026-09-15 23:59:59+02', 65.00);

INSERT INTO "DEMI_APPLICATION" (
    "ApplicationID", "StudentID", "ListingID", "ApplicationStatus",
    "VerificationEligibilityStatus", "DateSubmitted"
) VALUES
(1, 1, 1, 'Approved', 'Eligible', '2026-07-20 10:00:00+02'),
(2, 2, 2, 'Approved', 'Eligible', '2026-07-21 10:00:00+02'),
(3, 3, 1, 'Approved', 'Eligible', '2026-07-22 10:00:00+02'),
(4, 4, 4, 'Approved', 'Eligible', '2026-07-23 10:00:00+02'),
(5, 5, 5, 'Approved', 'Eligible', '2026-07-24 10:00:00+02'),
(6, 6, 6, 'Approved', 'Eligible', '2026-07-25 10:00:00+02'),
(7, 7, 3, 'Approved', 'Eligible', '2026-07-26 10:00:00+02'),
(8, 8, 7, 'Approved', 'Eligible', '2026-07-27 10:00:00+02'),
(9, 9, 9, 'Approved', 'Eligible', '2026-07-28 10:00:00+02'),
(10, 10, 8, 'Approved', 'Eligible', '2026-07-29 10:00:00+02');

INSERT INTO "DEMI_POSITION" (
    "PositionID", "ApplicationID", "PaymentScaleID",
    "TempBudgetPositionNo", "AccountingCombination", "TotalAllocatedHours",
    "StartDate", "TerminationDate"
) VALUES
(1, 1, 1, 'TBF-2026-001', '8412-4101-2104', 160, '2026-08-01', '2026-11-30'),
(2, 2, 1, 'TBF-2026-002', '8413-4101-2104', 160, '2026-08-01', '2026-11-30'),
(3, 3, 1, 'TBF-2026-003', '8412-4101-2104', 160, '2026-08-01', '2026-11-30'),
(4, 4, 2, 'TBF-2026-004', '8415-4101-2104', 160, '2026-08-01', '2026-11-30'),
(5, 5, 2, 'TBF-2026-005', '8414-4101-2104', 160, '2026-08-01', '2026-11-30'),
(6, 6, 2, 'TBF-2026-006', '8414-4101-2104', 160, '2026-08-01', '2026-11-30'),
(7, 7, 2, 'TBF-2026-007', '8414-4101-2104', 160, '2026-08-01', '2026-11-30');

INSERT INTO "WORK_SESSION" (
    "SessionID", "PositionID", "StartTime", "EndTime",
    "TotalHoursWorked", "EstimatedRemuneration", "LecturerApproval", "ActivityDescription"
) VALUES
(1, 1, '2026-08-04 08:00:00+02', '2026-08-04 12:00:00+02', 4.00, 347.00, true, 'Lab Setup - CMPG323'),
(2, 1, '2026-08-11 09:00:00+02', '2026-08-11 11:30:00+02', 2.50, 216.88, true, 'Tutoring Session 1 - CMPG323'),
(3, 2, '2026-08-05 08:00:00+02', '2026-08-05 12:00:00+02', 4.00, 347.00, true, 'Lab Setup - CMPG311'),
(4, 2, '2026-08-12 09:00:00+02', '2026-08-12 12:00:00+02', 3.00, 260.25, true, 'Tutoring Session 1 - CMPG311'),
(5, 3, '2026-08-06 08:00:00+02', '2026-08-06 12:00:00+02', 4.00, 347.00, true, 'Lab Setup - CMPG323'),
(6, 4, '2026-08-07 08:00:00+02', '2026-08-07 12:00:00+02', 4.00, 431.20, true, 'Lab Setup - REES211'),
(7, 5, '2026-08-08 08:00:00+02', '2026-08-08 12:00:00+02', 4.00, 431.20, true, 'Lab Setup - INGM311'),
(8, 6, '2026-08-09 08:00:00+02', '2026-08-09 12:00:00+02', 4.00, 431.20, true, 'Lab Setup - INGM412'),
(9, 7, '2026-08-10 08:00:00+02', '2026-08-10 12:00:00+02', 4.00, 431.20, true, 'Lab Setup - INGM222');

INSERT INTO "REMUNERATION_CLAIM" (
    "ClaimID", "ClaimReferenceNumber", "ApplicationID", "ModuleID",
    "PeriodStartDate", "PeriodEndDate", "TotalHoursClaimed",
    "TotalClaimAmount", "HourlyRateApplied", "ClaimStatus", "SubmissionDate"
) VALUES
(1, 'CLAIM-2026-08-001', 1, 1, '2026-08-01', '2026-08-24', 6.50, 563.88, 86.75, 'Verified', '2026-08-25 10:00:00+02'),
(2, 'CLAIM-2026-08-002', 2, 2, '2026-08-01', '2026-08-24', 7.00, 607.25, 86.75, 'Verified', '2026-08-25 10:30:00+02'),
(3, 'CLAIM-2026-08-003', 4, 4, '2026-08-01', '2026-08-24', 10.00, 1078.00, 107.80, 'Verified', '2026-08-25 11:00:00+02'),
(4, 'CLAIM-2026-08-004', 6, 9, '2026-08-01', '2026-08-24', 4.00, 431.20, 107.80, 'Verified', '2026-08-25 11:30:00+02'),
(5, 'CLAIM-2026-08-005', 5, 10, '2026-08-01', '2026-08-24', 6.00, 646.80, 107.80, 'Verified', '2026-08-25 12:00:00+02');

INSERT INTO "NOTIFICATION" (
    "NotificationID", "RecipientUserID", "NotificationType",
    "Subject", "Message", "IsRead"
) VALUES
(1, 1, 'Application Update', 'Application Approved', 'Your DEMI application has been approved.', true),
(2, 2, 'Application Update', 'Application Approved', 'Your DEMI application has been approved.', true),
(3, 3, 'Application Update', 'Application Approved', 'Your DEMI application has been approved.', false),
(4, 4, 'Claim Update', 'Claim Verified', 'Your remuneration claim has been verified.', true),
(5, 5, 'Claim Update', 'Claim Verified', 'Your remuneration claim has been verified.', false);

INSERT INTO "SECURITY_TOKEN" (
    "TokenID", "UserID", "JWT_Token", "IssuedAt", "ExpiresAt"
) VALUES
(1, 1, 'sample-jwt-token-1', '2026-08-25 08:00:00+02', '2026-08-26 08:00:00+02'),
(2, 2, 'sample-jwt-token-2', '2026-08-25 08:00:00+02', '2026-08-26 08:00:00+02');

COMMIT;
